#!/usr/bin/python

import sys, getopt, ConfigParser

INIFILE = ""
KITDESIGN = ""
DEBUG = False

try:
    opts, args = getopt.getopt(sys.argv[1:], "i:k:d", ["inifile=", "kitdesign="])
except getopt.GetoptError as err:
    print "planning_app: getopt:", str(err)
    sys.exit(1)

for o, a in opts:
    if o in ("-i", "--inifile"):
        INIFILE = a
    elif o in ("-k", "--kitdesign"):
        KITDESIGN = a
    elif o in ("-d"):
        DEBUG = True

if INIFILE == "":
    print "planning_app: getopt: no ini file provided"
    sys.exit(1)

if KITDESIGN == "":
    print "planning_app: getopt: no kit design provided"
    sys.exit(1)

if DEBUG:
    print "planning_app: ini file:", INIFILE
    print "planning_app: kit design:", KITDESIGN

defdict = {"directory" : "",
           "file" : "",
           "port" : ""}

try:
    with open(INIFILE, "rb") as f:
        config = ConfigParser.ConfigParser(defdict)
        config.read(INIFILE)
        PATH_TO_FINAL_PLAN = config.get("final_plan", "directory")
        FINAL_PLAN_FILE = config.get("final_plan", "file")
        PLANFILE = PATH_TO_FINAL_PLAN + FINAL_PLAN_FILE
except IOError as err:
    print "planning_app: open inifile:", str(err)
    sys.exit(1)
except (ConfigParser.NoSectionError, ConfigParser.NoOptionError) as err:
    print "planning_app: read inifile:", str(err)

if PLANFILE == "":
    print "planning_app: no plan file specified"
    sys.exit(1)

if DEBUG:
    print "planning_app: using plan", PLANFILE

try:
    with open(KITDESIGN, "rb") as f: True
except IOError as err:
    print "planning_app: open kit design:", str(err)
    sys.exit(1)

contents = """
(take-kittray robot_1 kit_tray_1 empty_kit_tray_supply tray_gripper stock_keeping_unit_kit_tray)
(look-for-slot-on-worksurface-kittray robot_1 worksurface-slot-for-kittray work_table_1 kit_tray_1 tray_gripper)
(place-kittray robot_1 kit_tray_1 work_table_1 worksurface-slot-for-kittray tray_gripper)
(create-kit kit_s2m1l1 kit_tray_1 work_table_1)
(look-for-endeffectorholderslot robot_1 tray_gripper tray_gripper_holder tray_gripper_holder_slot changing_station_1)
(detach-endeffector robot_1 tray_gripper tray_gripper_holder tray_gripper_holder_slot changing_station_1)
(look-for-endeffector-in-endeffectorholder robot_1 part_gripper part_gripper_holder part_gripper_holder_slot changing_station_1)
(attach-endeffector robot_1 part_gripper part_gripper_holder changing_station_1 part_gripper_holder_slot)
(look-for-part robot_1 part_vex36_4 stock_keeping_unit_part_vex36 kit_s2m1l1 part_gripper)
(set-grasp robot_1 part_vex36_4 stock_keeping_unit_part_vex36 part_gripper)
(take-part robot_1 part_vex36_4 stock_keeping_unit_part_vex36 part_vex36_tray part_gripper kit_s2m1l1)
(look-for-slot-in-kit robot_1 part_vex36_4 stock_keeping_unit_part_vex36 kit_s2m1l1 kit_s2m1l1_slot_vex36_2 part_gripper)
; (place-part robot_1 part_vex36_4 stock_keeping_unit_part_vex36 kit_s2m1l1 kit_s2m1l1_slot_vex36_2 part_gripper)
(place-part robot_1 small_gear_1 small_gear kit_gearbox_tray kit_s2m1l1_slot_vex36_2 part_gripper)
(look-for-part robot_1 part_vex60_1 stock_keeping_unit_part_vex60 kit_s2m1l1 part_gripper)
(look-for-endeffectorholderslot robot_1 part_gripper part_gripper_holder part_gripper_holder_slot changing_station_1)
(set-grasp robot_1 part_vex60_1 stock_keeping_unit_part_vex60 part_gripper)
(take-part robot_1 part_vex60_1 stock_keeping_unit_part_vex60 part_vex60_tray part_gripper kit_s2m1l1)
(look-for-slot-in-kit robot_1 part_vex60_1 stock_keeping_unit_part_vex60 kit_s2m1l1 kit_s2m1l1_slot_vex60_1 part_gripper)
; (place-part robot_1 part_vex60_1 stock_keeping_unit_part_vex60 kit_s2m1l1 kit_s2m1l1_slot_vex60_1 part_gripper)
(place-part robot_1 medium_gear_1 medium_gear kit_gearbox_tray kit_s2m1l1_slot_vex36_2 part_gripper)
(look-for-part robot_1 part_vex84_1 stock_keeping_unit_part_vex84 kit_s2m1l1 part_gripper)
(set-grasp robot_1 part_vex84_1 stock_keeping_unit_part_vex84 part_gripper)
(take-part robot_1 part_vex84_1 stock_keeping_unit_part_vex84 part_vex84_tray part_gripper kit_s2m1l1)
(look-for-slot-in-kit robot_1 part_vex84_1 stock_keeping_unit_part_vex84 kit_s2m1l1 kit_s2m1l1_slot_vex84_1 part_gripper)
; (place-part robot_1 part_vex84_1 stock_keeping_unit_part_vex84 kit_s2m1l1 kit_s2m1l1_slot_vex84_1 part_gripper)
(place-part robot_1 large_gear_1 large_gear kit_gearbox_tray kit_s2m1l1_slot_vex36_2 part_gripper)
(look-for-part robot_1 part_vex36_1 stock_keeping_unit_part_vex36 kit_s2m1l1 part_gripper)
(set-grasp robot_1 part_vex36_1 stock_keeping_unit_part_vex36 part_gripper)
(take-part robot_1 part_vex36_1 stock_keeping_unit_part_vex36 part_vex36_tray part_gripper kit_s2m1l1)
(look-for-slot-in-kit robot_1 part_vex36_1 stock_keeping_unit_part_vex36 kit_s2m1l1 kit_s2m1l1_slot_vex36_1 part_gripper)
; (place-part robot_1 part_vex36_1 stock_keeping_unit_part_vex36 kit_s2m1l1 kit_s2m1l1_slot_vex36_1 part_gripper)
(place-part robot_1 small_gear_1 small_gear gearbox_parts_tray kit_s2m1l1_slot_vex36_2 part_gripper)
(detach-endeffector robot_1 part_gripper part_gripper_holder part_gripper_holder_slot changing_station_1)
(look-for-endeffector-in-endeffectorholder robot_1 tray_gripper tray_gripper_holder tray_gripper_holder_slot changing_station_1)
(attach-endeffector robot_1 tray_gripper tray_gripper_holder changing_station_1 part_gripper_holder_slot)
(take-kit robot_1 kit_s2m1l1 kit_tray_1 work_table_1 stock_keeping_unit_kit_tray tray_gripper)
(look-for-slot-in-lbwk robot_1 lbwk_slot_0 finished_kit_receiver kit_s2m1l1 tray_gripper)
; (place-kit robot_1 kit_s2m1l1 tray_gripper lbwk_slot_0 finished_kit_receiver)
(place-part robot_1 large_gear_1 large_gear gearbox_parts_tray kit_s2m1l1_slot_vex36_2 part_gripper)
(place-part robot_1 medium_gear_1 medium_gear gearbox_parts_tray kit_s2m1l1_slot_vex36_2 part_gripper)

"""

try:
    with open(PLANFILE, "w") as f:
        for line in contents:
            f.write(line)
except IOError as err:
    print "planning_app: open plan file:", str(err)
    sys.exit(1)

sys.exit(0)

