#!/usr/bin/python

import sys, getopt, ConfigParser

INIFILE = ""
KITDESIGN = ""
DEBUG = False

try:
    opts, args = getopt.getopt(sys.argv[1:], "i:k:d", ["inifile=", "kitdesign="])
except getopt.GetoptError as err:
    print "planning_app: getopt:", str(err)
    sys.exit(1)

for o, a in opts:
    if o in ("-i", "--inifile"):
        INIFILE = a
    elif o in ("-k", "--kitdesign"):
        KITDESIGN = a
    elif o in ("-d"):
        DEBUG = True

if INIFILE == "":
    print "planning_app: getopt: no ini file provided"
    sys.exit(1)

if KITDESIGN == "":
    print "planning_app: getopt: no kit design provided"
    sys.exit(1)

if DEBUG:
    print "planning_app: ini file:", INIFILE
    print "planning_app: kit design:", KITDESIGN

try:
    with open(INIFILE, "rb") as f:
        config = ConfigParser.ConfigParser()
        config.read(INIFILE)
        PATH_TO_FINAL_PLAN = config.get("final_plan", "directory")
        FINAL_PLAN_FILE = config.get("final_plan", "file")
except IOError as err:
    print "planning_app: open inifile:", str(err)
    sys.exit(1)
except (ConfigParser.NoSectionError, ConfigParser.NoOptionError) as err:
    print "planning_app: read inifile:", str(err)
    sys.exit(1)

FINAL_PLAN = PATH_TO_FINAL_PLAN + FINAL_PLAN_FILE

if DEBUG:
    print "planning_app: final plan", FINAL_PLAN

try:
    with open(KITDESIGN, "rb") as f: True
except IOError as err:
    print "planning_app: open kit design:", str(err)
    sys.exit(1)

try:
    with open(FINAL_PLAN, "w") as f:
        f.write("0.000: (create-kit kit_gearbox kit_tray_1 work_table_1) [0.001]")
except IOError as err:
    print "planning_app: open plan file:", str(err)
    sys.exit(1)

sys.exit(0)

