#!/usr/bin/python

import sys, time, getopt, re, socket, ConfigParser, StringIO, xml.etree.ElementTree as ET

from crcl import *

xmldec = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>"
uri = "http://www.w3.org/2001/XMLSchema-instance"
xsi = "{" + uri + "}"
dict = {"xmlns:xsi" : uri}

INIFILE = ""
PLANFILE = ""
ROBOT_PORT = ""
ROBOT_HOST = ""
GRIPPER_PORT = ""
GRIPPER_HOST = ""
DEBUG = False

XAXIS = VectorType(1, 0, 0)
ZAXIS = VectorType(0, 0, 1)

def readStatus(port):
    size = 1024

    try: data = port.recv(size)
    except: return False, 0, CommandStateType.ERROR

    try:
        tree = ET.parse(StringIO.StringIO(data))
        root = tree.getroot()
    except: return False, 0, CommandStateType.ERROR

    for child in root:
        if child.tag == "CommandStatus":
            cid = int(child.findtext("CommandID"))
            sid = int(child.findtext("StatusID"))
            cs = toCommandStateType(child.findtext("CommandState"))
            return True, cid, cs
        else: return False, 0, CommandStateType.ERROR

def Attach_Endeffector(toks, robot_port, gripper_port):
    # print toks
    return True

def Create_Kit(toks, robot_port, gripper_port):
    # print toks
    return True

def Detach_Endeffector(toks, robot_port, gripper_port):
    # print toks
    return True

def Look_For_Part(toks, robot_port, gripper_port):
    # print toks
    return True

def Move_Over_Kit(toks, robot_port, gripper_port):
    # print toks
    return True

def Move_Over_Kittray(toks, robot_port, gripper_port):
    # print toks
    return True

def Move_Over_Part(toks, robot_port, gripper_port):
    out = ""
    # (move-over-part robot_1 part_gripper gearbox_base_tray gearbox_base_1 stock_keeping_unit_gearbox_base)
    if len(toks) < 6: return
    print toks[0], "using", toks[1], "with", toks[2], "to location", toks[3], "to get", toks[4], "of SKU", toks[5]
    return True

def Place_Kit(toks, robot_port, gripper_port):
    # print toks
    return True

def Place_Kittray(toks, robot_port, gripper_port):
    # print toks
    return True

def Place_Part(toks, robot_port, gripper_port):
    # (place-part robot_1 gearbox_base_1 stock_keeping_unit_gearbox_base kit_gearbox part_gripper work_table_1 shaft_tray)
    if len(toks) < 8: return
    print toks[0], "using", toks[1], "for part", toks[2], "of SKU", toks[3], "to location", toks[4], "using", toks[5], "if on", toks[6], "and", toks[7]

    # //! Configure gripper for pre-grasp
    # pm.demo->Decouple(curtool);
    m = OpenToolChangerType(101)
    gripper_port.send(str(m))
    fail = time.time() + 3
    while True:
        ret, cid, cs = readStatus(gripper_port)
        if (ret == True) and (cid == 101):
            if cs == CommandStateType.DONE: break
            elif cs == CommandStateType.ERROR: return False
        if time.time() > fail: return False
        time.sleep(1)

    # pm.demo->Couple(curtool);
    m = CloseToolChangerType(102)
    gripper_port.send(str(m))
    time.sleep(1)
    # //! Open gripper
    # pm.demo->SetTool (0.9);
    m = SetEndEffectorParametersType(103, ParameterSettingType("set", 0.9))
    gripper_port.send(str(m))
    time.sleep(1)
    # //! Move over part at z position
    # pm.demo->MoveTo (poseMe)
    m = MoveThroughToType(104, False, [PoseOnlyLocationType(PointType(0,0,0), XAXIS, ZAXIS)])
    robot_port.send(str(m))
    time.sleep(1)
    # //! Grasp part
    # pm.demo->SetTool (0.1);
    m = SetEndEffectorParametersType(105, ParameterSettingType("set", 0.1))
    gripper_port.send(str(m))
    time.sleep(1)
    # //! Move over the part at z position
    # pm.demo->MoveTo (poseMe)
    m = MoveThroughToType(106, False, [PoseOnlyLocationType(PointType(0,0,0), XAXIS, ZAXIS)])
    robot_port.send(str(m))
    time.sleep(1)
    return True

def Take_Kit(toks, robot_port, gripper_port):
    # print toks
    return True

def Take_Kittray(toks, robot_port, gripper_port):
    # print toks
    return True

def Take_Part(toks, robot_port, gripper_port):
    # (take-part robot_1 gearbox_base_1 stock_keeping_unit_gearbox_base gearbox_base_tray part_gripper kit_gearbox)
    if len(toks) < 7: return
    print toks[0], "using", toks[1], "for part", toks[2], "of SKU", toks[3], "from location", toks[4], "using", toks[5], "if", toks[6], "exists"
    # //! Configure gripper for pre-grasp
    # pm.demo->Decouple(curtool);
    # pm.demo->Couple(curtool);
    # //! Open gripper
    # pm.demo->SetTool (0.9);
    # //! Move over part at z position
    # pm.demo->MoveTo (poseMe)
    # //! Grasp part
    # pm.demo->SetTool (0.1);
    # //! Move over the part at z position
    # pm.demo->MoveTo (poseMe)
    return True

# --- the dictionary associating PDDL commands with handler functions ---

funcdict = {
    "attach-endeffector" : Attach_Endeffector,
    "create-kit" : Create_Kit,
    "detach-endeffector" : Detach_Endeffector,
    "look-for-part" : Look_For_Part,
    "move-over-kit" : Move_Over_Kit,
    "move-over-kittray" : Move_Over_Kittray,
    "move-over-part" : Move_Over_Part,
    "place-kit" : Place_Kit,
    "place-kittray" : Place_Kittray,
    "place-part" : Place_Part,
    "take-kit" : Take_Kit,
    "take-kittray" : Take_Kittray,
    "take-part" : Take_Part
}

# parseLine looks up the handler functions and calls them with
# the line and the socket ports to the robot and gripper subordinates

def parseLine(line, robot_socket, gripper_socket):

    toks = str.split(line)
    num = len(toks)
    if num == 0: return False

    func = funcdict.get(toks[0], None)
    if (func != None): return func(toks, robot_socket, gripper_socket)

    print "unknown command", toks[0]
    return False

# --- Main ---

try:
    opts, args = getopt.getopt(sys.argv[1:], "i:f:r:R:g:G:d", ["inifile=", "file=", "robot=", "robothost=", "gripper=", "gripperhost="])
except getopt.GetoptError, err:
    print "plan_exec_app:", str(err)
    sys.exit(1)

for o, a in opts:
    if o in ("-i", "--inifile"):
        INIFILE = a
    elif o in ("-f", "--file"):
        PLANFILE = a
    elif o in ("-r", "--robot"):
        ROBOT_PORT = a
    elif o in ("-R", "--robothost"):
        ROBOT_HOST = a
    elif o in ("-g", "--gripper"):
        GRIPPER_PORT = a
    elif o in ("-G", "--gripperhost"):
        GRIPPER_HOST = a
    elif o in ("-d"):
        DEBUG = True

defdict = {"directory" : "",
           "file" : "",
           "port" : "",
           "host" : ""}

if INIFILE != "":
    try:
        with open(INIFILE, "rb") as f:
            config = ConfigParser.ConfigParser(defdict)
            config.read(INIFILE)
            if PLANFILE == "":
                PATH_TO_FINAL_PLAN = config.get("final_plan", "directory")
                FINAL_PLAN_FILE = config.get("final_plan", "file")
                PLANFILE = PATH_TO_FINAL_PLAN + FINAL_PLAN_FILE
            if ROBOT_PORT == "":
                ROBOT_PORT = config.get("robot_prim", "port")
            if ROBOT_HOST == "":
                ROBOT_HOST = config.get("robot_prim", "host")
            if GRIPPER_PORT == "":
                GRIPPER_PORT = config.get("gripper_prim", "port")
            if GRIPPER_HOST == "":
                GRIPPER_HOST = config.get("gripper_prim", "host")
    except IOError as err:
        print "robot_prim: open inifile:", str(err)
        sys.exit(1)
    except (ConfigParser.NoSectionError, ConfigParser.NoOptionError) as err:
        print "robot_prim: read inifile:", str(err)
    except:
        print "robot_prim: inifile error"
        sys.exit(1)

if PLANFILE == "":
    print "plan_exec_app: no plan file specified"
    sys.exit(1)

if ROBOT_PORT == "":
    print "plan_exec_app: no robot port provided"
    sys.exit(1)

if ROBOT_HOST == "": ROBOT_HOST = "localhost"

if GRIPPER_PORT == "":
    print "plan_exec_app: no gripper port provided"
    sys.exit(1)

if GRIPPER_HOST == "": GRIPPER_HOST = "localhost"

if DEBUG:
    print "plan_exec_app: plan file:", PLANFILE
    print "plan_exec_app: robot host:", ROBOT_HOST, ", port:", ROBOT_PORT
    print "plan_exec_app: gripper host:", GRIPPER_HOST, ", port:", GRIPPER_PORT

# FIXME
# Connect to robot, gripper
# Spawn threads for each to read status and update global RCS header vars
# Write commands to them in the handlers

try:
    robot_socket = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    robot_socket.connect((ROBOT_HOST, int(ROBOT_PORT)))
except IOError as err:
    print "plan_exec_app: can't connect to robot controller", ROBOT_HOST, "on port", ROBOT_PORT, ":", str(err)
    sys.exit(1)

try:
    gripper_socket = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    gripper_socket.connect((GRIPPER_HOST, int(GRIPPER_PORT)))
except IOError as err:
    print "plan_exec_app: can't connect to gripper controller", GRIPPER_HOST, "on port", GRIPPER_PORT, ":", str(err)
    sys.exit(1)

try:
    f = open(PLANFILE, "rb")
except IOError as err:
    print "plan_exec_app: can't open", PLANFILE, ":", str(err)
    sys.exit(1)

for line in f:
    # this means match zero or more chars, then a literal '(',
    # then set up a target with () enclosing a match of anything,
    # then match a literal ')', then anything
    m = re.match(".*\((.*)\).*", line)
    if m != None:
        if DEBUG: print "plan_exec_app: parsing line", m.group(1)
        retval = parseLine(m.group(1), robot_socket, gripper_socket)
        if retval == False:
            print "plan_exec_app: error handling", m.group(1)
            sys.exit(1)

sys.exit(0)
