.TH "/usr/local/michalos/github/usnistgov/el-robotics-core/nist_fanuc/src/AsioCrclServer.cpp" 3 "Fri Apr 15 2016" "CRCL FANUC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/usr/local/michalos/github/usnistgov/el-robotics-core/nist_fanuc/src/AsioCrclServer.cpp \- 
.PP
The \fBCAsioCrclSession\fP provides an boost asio session ( which listens for each connected client)\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'CrclConfig\&.h'\fP
.br
\fC#include 'AsioCrclServer\&.h'\fP
.br
\fC#include <boost/exception/all\&.hpp>\fP
.br
\fC#include <boost/regex\&.hpp>\fP
.br
\fC#include 'Globals\&.h'\fP
.br
\fC#include 'Controller\&.h'\fP
.br

.SS "Variables"

.in +1c
.ti -1c
.RI "boost::asio::io_service \fBmyios\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
The \fBCAsioCrclSession\fP provides an boost asio session ( which listens for each connected client)\&. 


.SH "Variable Documentation"
.PP 
.SS "boost::asio::io_service myios"

.SH "Author"
.PP 
Generated automatically by Doxygen for CRCL FANUC from the source code\&.
