.TH "/home/michalos/catkin_ws/src/nist_fanuc/src/AsioCrclServer.cpp" 3 "Thu Mar 10 2016" "CRCL FANUC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/michalos/catkin_ws/src/nist_fanuc/src/AsioCrclServer.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'CrclConfig\&.h'\fP
.br
\fC#include 'AsioCrclServer\&.h'\fP
.br
\fC#include <boost/exception/all\&.hpp>\fP
.br
\fC#include <boost/regex\&.hpp>\fP
.br
\fC#include 'Globals\&.h'\fP
.br
\fC#include 'Controller\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBS_OK\fP   0"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "boost::asio::io_service \fBmyios\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define S_OK   0"

.SH "Variable Documentation"
.PP 
.SS "boost::asio::io_service myios"

.SH "Author"
.PP 
Generated automatically by Doxygen for CRCL FANUC from the source code\&.
