.TH "/usr/local/michalos/github/usnistgov/el-robotics-core/nist_fanuc/src/Controller.cpp" 3 "Fri Apr 15 2016" "CRCL FANUC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/usr/local/michalos/github/usnistgov/el-robotics-core/nist_fanuc/src/Controller.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'Controller\&.h'\fP
.br
\fC#include <boost/exception/all\&.hpp>\fP
.br
\fC#include <boost/thread\&.hpp>\fP
.br
\fC#include <strstream>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include 'urdf_model/rosmath\&.h'\fP
.br
\fC#include 'CrclInterface\&.h'\fP
.br
\fC#include 'RvizMarker\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "\fBRCS\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBBOOST_ALL_NO_LIB\fP"
.br
.ti -1c
.RI "#define \fBMARKERS\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "::CRCLProgramType::MiddleCommand_sequence & \fBRCS::DummyInit\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBALogger\fP \fBLogger\fP"
.br
.ti -1c
.RI "boost::mutex \fBRCS::cncmutex\fP"
.br
.ti -1c
.RI "\fBRCS::CController\fP \fBRCS::Controller\fP (\fBDEFAULT_LOOP_CYCLE\fP)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define BOOST_ALL_NO_LIB"

.SS "#define MARKERS"

.SH "Variable Documentation"
.PP 
.SS "\fBALogger\fP Logger"

.SH "Author"
.PP 
Generated automatically by Doxygen for CRCL FANUC from the source code\&.
