.TH "/usr/local/michalos/github/usnistgov/el-robotics-core/nist_fanuc/include/nist_fanuc/CrclInterface.h" 3 "Fri Apr 15 2016" "CRCL FANUC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/usr/local/michalos/github/usnistgov/el-robotics-core/nist_fanuc/include/nist_fanuc/CrclInterface.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include 'crcl\&.h'\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <vector>\fP
.br
\fC#include 'Globals\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCrcl::CrclDelegateInterface\fP"
.br
.RI "\fI\fBCrclDelegateInterface\fP parses \fBCrcl\fP commands and interprets into robot motion\&. https://github.com/usnistgov/crcl/blob/master/doc/Reference.md\&. \fP"
.ti -1c
.RI "class \fBCrcl::CrclClientCmdInterface\fP"
.br
.RI "\fI\fBCrclClientCmdInterface\fP generates \fBCrcl\fP XML command message from to send to a \fBCrcl\fP server\&. \fP"
.ti -1c
.RI "class \fBCrcl::CrclStatusMsgInterface\fP"
.br
.RI "\fI\fBCrclStatusMsgInterface\fP parses a \fBCrcl\fP XML status message from a \fBCrcl\fP server\&. \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "\fBCrcl\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CRCL FANUC from the source code\&.
