.TH "Crcl::GripperStatus" 3 "Fri Apr 15 2016" "CRCL FANUC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Crcl::GripperStatus \- 
.PP
\fBGripperStatus\fP dummy class for future gripper information\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <crcl\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::string \fB_name\fP"
.br
.ti -1c
.RI "double \fB_dPosition\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBGripperStatus\fP dummy class for future gripper information\&. 
.SH "Member Data Documentation"
.PP 
.SS "double Crcl::GripperStatus::_dPosition"

.SS "std::string Crcl::GripperStatus::_name"


.SH "Author"
.PP 
Generated automatically by Doxygen for CRCL FANUC from the source code\&.
