.TH "Crcl::JointReport" 3 "Fri Apr 15 2016" "CRCL FANUC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Crcl::JointReport \- 
.PP
\fBJointReport\fP dummy class for future customization of \fBCrcl\fP status reports\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <crcl\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "size_t \fB_nJointNumber\fP"
.br
.ti -1c
.RI "bool \fB_bReportPosition\fP"
.br
.ti -1c
.RI "bool \fB_bReportTorqueOrForce\fP"
.br
.ti -1c
.RI "bool \fB_bReportVelocity\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBJointReport\fP dummy class for future customization of \fBCrcl\fP status reports\&. 
.SH "Member Data Documentation"
.PP 
.SS "bool Crcl::JointReport::_bReportPosition"

.SS "bool Crcl::JointReport::_bReportTorqueOrForce"

.SS "bool Crcl::JointReport::_bReportVelocity"

.SS "size_t Crcl::JointReport::_nJointNumber"


.SH "Author"
.PP 
Generated automatically by Doxygen for CRCL FANUC from the source code\&.
