.TH "/usr/local/michalos/github/usnistgov/el-robotics-core/nist_fanuc/src/CrclInterface.cpp" 3 "Fri Apr 15 2016" "CRCL FANUC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/usr/local/michalos/github/usnistgov/el-robotics-core/nist_fanuc/src/CrclInterface.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'CrclConfig\&.h'\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <fstream>\fP
.br
\fC#include <sstream>\fP
.br
\fC#include <math\&.h>\fP
.br
\fC#include <xercesc/dom/DOM\&.hpp>\fP
.br
\fC#include <xercesc/util/PlatformUtils\&.hpp>\fP
.br
\fC#include <xercesc/framework/XMLGrammarPoolImpl\&.hpp>\fP
.br
\fC#include <boost/regex\&.hpp>\fP
.br
\fC#include <boost/exception/all\&.hpp>\fP
.br
\fC#include 'CrclInterface\&.h'\fP
.br
\fC#include 'Globals\&.h'\fP
.br
\fC#include 'Controller\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB_USE_MATH_DEFINES\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define _USE_MATH_DEFINES"

.SH "Author"
.PP 
Generated automatically by Doxygen for CRCL FANUC from the source code\&.
