.TH "Crcl::CrclStatusMsgInterface" 3 "Fri Apr 15 2016" "CRCL FANUC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Crcl::CrclStatusMsgInterface \- 
.PP
\fBCrclStatusMsgInterface\fP parses a \fBCrcl\fP XML status message from a \fBCrcl\fP server\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <CrclInterface\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCrclStatusMsgInterface\fP ()"
.br
.ti -1c
.RI "void \fBParseCRCLStatus\fP (std::string filename)"
.br
.ti -1c
.RI "void \fBParseCRCLStatusString\fP (std::string str)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBCrclStatus\fP \fB_status\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBCrclStatusMsgInterface\fP parses a \fBCrcl\fP XML status message from a \fBCrcl\fP server\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Crcl::CrclStatusMsgInterface::CrclStatusMsgInterface ()\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void CrclStatusMsgInterface::ParseCRCLStatus (std::stringfilename)"

.SS "void CrclStatusMsgInterface::ParseCRCLStatusString (std::stringstr)"

.SH "Member Data Documentation"
.PP 
.SS "\fBCrclStatus\fP Crcl::CrclStatusMsgInterface::_status"


.SH "Author"
.PP 
Generated automatically by Doxygen for CRCL FANUC from the source code\&.
