.TH "/usr/local/michalos/github/usnistgov/el-robotics-core/nist_fanuc/src/fanucdemo.cpp" 3 "Fri Apr 15 2016" "CRCL FANUC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/usr/local/michalos/github/usnistgov/el-robotics-core/nist_fanuc/src/fanucdemo.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <boost/format\&.hpp>\fP
.br
\fC#include 'fanucdemo\&.h'\fP
.br
\fC#include <string>\fP
.br
\fC#include 'sys/stat\&.h'\fP
.br
\fC#include 'fcntl\&.h'\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <sstream>\fP
.br
\fC#include <xercesc/dom/DOM\&.hpp>\fP
.br
\fC#include <xercesc/util/PlatformUtils\&.hpp>\fP
.br
\fC#include <xercesc/framework/XMLGrammarPoolImpl\&.hpp>\fP
.br
\fC#include 'MotionControl\&.h'\fP
.br
\fC#include 'AsioCrclServer\&.h'\fP
.br
\fC#include 'Globals\&.h'\fP
.br
\fC#include 'Controller\&.h'\fP
.br
\fC#include 'CrclInterface\&.h'\fP
.br
\fC#include 'Kinematics\&.h'\fP
.br
\fC#include 'urdf_model/eigenmath\&.h'\fP
.br
\fC#include 'Communication\&.h'\fP
.br
\fC#include 'Setup\&.h'\fP
.br
\fC#include 'moveit\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "std::string \fBDumpUrdfPose\fP (const urdf::Pose &p)"
.br
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "std::string DumpUrdfPose (const urdf::Pose &p)\fC [inline]\fP"

.SS "int main (intargc, char **argv)"

.SH "Author"
.PP 
Generated automatically by Doxygen for CRCL FANUC from the source code\&.
