.TH "/usr/local/michalos/github/usnistgov/el-robotics-core/nist_fanuc/src/Globals.cpp" 3 "Fri Apr 15 2016" "CRCL FANUC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/usr/local/michalos/github/usnistgov/el-robotics-core/nist_fanuc/src/Globals.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'Globals\&.h'\fP
.br
\fC#include <map>\fP
.br
\fC#include <iostream>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBDebugBreak\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBCGlobals\fP \fBGlobals\fP"
.br
.ti -1c
.RI "\fBALogger\fP \fBLogFile\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void DebugBreak ()"
global definition of windows DebugBreak equivalent\&. 
.SH "Variable Documentation"
.PP 
.SS "\fBCGlobals\fP Globals"
global definition of globals 
.SS "\fBALogger\fP LogFile"

.SH "Author"
.PP 
Generated automatically by Doxygen for CRCL FANUC from the source code\&.
