.TH "/home/michalos/catkin_ws/src/nist_fanuc/src/Globals.cpp" 3 "Fri Mar 11 2016" "CRCL FANUC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/michalos/catkin_ws/src/nist_fanuc/src/Globals.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'Globals\&.h'\fP
.br
\fC#include <map>\fP
.br
\fC#include <iostream>\fP
.br

.SS "Variables"

.in +1c
.ti -1c
.RI "\fBCGlobals\fP \fBGlobals\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "\fBCGlobals\fP Globals"
global definition of globals 
.SH "Author"
.PP 
Generated automatically by Doxygen for CRCL FANUC from the source code\&.
