.TH "/usr/local/michalos/github/usnistgov/el-robotics-core/nist_fanuc/include/nist_fanuc/Logging.h" 3 "Fri Apr 15 2016" "CRCL FANUC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/usr/local/michalos/github/usnistgov/el-robotics-core/nist_fanuc/include/nist_fanuc/Logging.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <map>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBALogger\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBLOGONCE\fP   static long nLog ## __LINE__ = 0; if ( 0 == nLog ## __LINE__++ )"
.br
.ti -1c
.RI "#define \fBLOGNAME\fP(F, L)   \fBLineName\fP(F, L)"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "std::string \fBLineName\fP (std::string file, int line)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBALogger\fP \fBLogger\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define LOGNAME(F, L)   \fBLineName\fP(F, L)"

.SS "#define LOGONCE   static long nLog ## __LINE__ = 0; if ( 0 == nLog ## __LINE__++ )"

.SH "Function Documentation"
.PP 
.SS "std::string LineName (std::stringfile, intline)\fC [inline]\fP"

.SH "Variable Documentation"
.PP 
.SS "\fBALogger\fP Logger"

.SH "Author"
.PP 
Generated automatically by Doxygen for CRCL FANUC from the source code\&.
