.TH "md_Installation" 3 "Thu Mar 17 2016" "CRCL FANUC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_Installation \- Installation Readme 

.SS "1) Set up ROS with Descartes and ROS Industrial "
.PP
Copy repositories from https://github.com/ros-industrial: 
.PP
.nf
fanuc
fanuc experimental
motoman
ros industrial core

.fi
.PP
.PP
Repositories from ROS-I Consortium https://github.com/ros-industrial-consortium github site: 
.PP
.nf
descartes
descartes_tutorials

.fi
.PP
.PP
.SS "2) Installing Xerces c with Ubuntu "
.PP
https://www.daniweb.com/hardware-and-software/linux-and-unix/threads/409769/ubuntu-11-10-xerces-c As far as I'm aware libxerces is the same as pretty much any other library in Debian based systems\&. It should be available in the repositories (the exact version will depend on which version of Ubuntu you're running)\&.
.PP
You can use apt-get to install the packages for the library and the dev files\&. Then to use them in your C/C++ programs you simply #include the appropriate headers and link with the library when compiling/linking\&. 
.PP
.nf
sudo apt-get update
apt-cache search libxerces
sudo apt-get install libxerces-c3.1 libxerces-c-dev

.fi
.PP
.PP
Need include file path CMakeLists\&.txt: 
.PP
.nf
include_directories(/usr/include/xercesc)

.fi
.PP
.PP
Link library in CMakeLists\&.txt: 
.PP
.nf
link_directories(/usr/lib/x86_64-linux-gnu/)

.fi
.PP
.PP
Need to link against libxerces\&.a in CMakeLists\&.txt: 
.PP
.nf
target_link_libraries(nist_fanuc 
libxerces-c.a  
${catkin_LIBRARIES}
${Boost_LIBRARIES}
)

.fi
.PP
.PP
.SS "3) Installing CodeSynthesis XSD "
.PP
http://www.codesynthesis.com/products/xsd/download.xhtml
.IP "1." 4
Chose the linux deb install file that matches your computer (below 64 bit amd)\&.
.IP "2." 4
Download xsd_4\&.0\&.0-1_amd64\&.deb and it will say open with Ubuntu Software Center
.IP "3." 4
Click to install, authenticate and add /usr/include/xsd/cxx/xml as include path\&.
.PP
.PP
Need include file path in CMakeLists\&.txt: 
.PP
.nf
include_directories(/usr/include/xsd/cxx/xml)

.fi
.PP
.PP
If you cannot run Ubuntu software centerto install CodeSynthesis, you can download the source and install it\&. You need to go to the web page: http://www.codesynthesis.com/products/xsd/download.xhtml and select: 
.PP
.nf
xsd-4.0.0-x86_64-linux-gnu.tar.bz2

.fi
.PP
.PP
It will be saved into /usr/local/downloads, but you can save it anywhere\&. Then cd to where you saved it, and do this: 
.PP
.nf
tar --bzip2 -xvf xsd-4.0.0-x86_64-linux-gnu.tar.bz2 (dash-dash bzip2, dash-xvf)

.fi
.PP
.PP
It will create a directory xsd-4\&.0\&.0-x86_64-linux-gnu\&.
.PP
Make a symbolic link: 
.PP
.nf
ln -s <path/to/xsd-4.0.0-x86_64-linux-gnu/libxsd/xsd /usr/local/include/xsd
.fi
.PP
 
