.TH "md_markdown_FanucRobotOperationInstructions" 3 "Fri Apr 15 2016" "CRCL FANUC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_markdown_FanucRobotOperationInstructions \- Fanuc LRMate 200iD Robot Operation Instructions 

.SS "Powerup: "
.PP
.IP "1." 4
Turn on power on front of controller (keyed)
.IP "2." 4
If auto mode, make sure teach pendant upper left corner knob is \fBOFF\fP
.IP "3." 4
If in fault- hold deadman switch halfway, Hold [\fBShift\fP], press [\fBReset\fP] key
.IP "4." 4
reset to local mode \fCMenu -> [32] Remote/Local/\&.\&.\&. [F4] Local [Enter]\fP
.IP "5." 4
Start ROS programs \fC[Teach][Select] => scroll down to ROS, number 39 hit [Enter]\fP (starts 2 programs)
.IP "6." 4
Cycle start \fCGreen Auto button on front controller panel, press/release, green Light should go on\fP\&.
.PP
.PP
.SS "Powerdown: "
.PP
.IP "1." 4
Kill ROS programs - DO TWICE - 2 programs running \fC[FCNT] -> 1 -> [ENTER]\fP \fC[FCNT] -> 1 -> [ENTER]\fP
.PP
.PP
.SS "Fault Recovery "
.PP
If fanuc controller faulted, you have to manually reset the joint(s) to a 'safe' position:
.PP
.IP "2." 4
Turn controller box to teach pendant from auto
.IP "3." 4
hold deadman switch half-on, [\fBSHIFT\fP] Hold, hit [\fBReset\fP]
.IP "4." 4
Now move robot - +/- joint key or xyz key
.IP "5." 4
Note to increase traversal- feedoverride in green xx% field in upper right corner
.PP
.PP
.SS "Run ROS Fanuc demo "
.PP
.PP
.nf
roslaunch fanuc_lrmate200id_moveit_config  moveit_planning_execution.launch 
    sim:=false   robot_ip:=129.6.78.111
.fi
.PP
.PP
.SS "Run RVIZ roslaunch with Fanuc LRMate 200id "
.PP
\fBFIXME\fP 
.PP
.nf
#!/bin/bash
source .../catkin_ws/devel/setup.bash
roslaunch nist_fanuc lrmate200id_sim.launch

sleep 100

.fi
.PP
.PP
.SS "Launch file: "
.PP
.PP
.nf
<?xml version="1.0"?>
<launch>

  <arg name="sim" default="true" />

  <include file="$(find fanuc_lrmate200id_moveit_config)/launch/moveit_planning_execution.launch">
    <arg name="sim" value="$(arg sim)"/>
  </include>

</launch>
.fi
.PP
.PP
.SS "Fanuc ROS installation tutorial - I "
.PP
Web stop #1: 
.PP
.nf
            http://wiki.ros.org/fanuc?distro=indigo

.fi
.PP
.PP
.SS "Fanuc ROS installation tutorial - II "
.PP
Web stop #2: 
.PP
.nf
            http://wiki.ros.org/fanuc/Tutorials/hydro/Installation

.fi
.PP
.PP
The “Next” link at the bottom takes you to the next in the series\&. 
