.TH "/usr/local/michalos/github/usnistgov/el-robotics-core/nist_fanuc/include/nist_fanuc/MotionControl.h" 3 "Fri Apr 15 2016" "CRCL FANUC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/usr/local/michalos/github/usnistgov/el-robotics-core/nist_fanuc/include/nist_fanuc/MotionControl.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include <control_msgs/FollowJointTrajectoryAction\&.h>\fP
.br
\fC#include <actionlib/client/simple_action_client\&.h>\fP
.br
\fC#include 'RCS\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMotionControl\fP"
.br
.RI "\fI\fBMotionControl\fP is a class that contains some useful motion control methods\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CRCL FANUC from the source code\&.
