.TH "/usr/local/michalos/github/usnistgov/el-robotics-core/nist_fanuc/include/nist_fanuc/moveit.h" 3 "Fri Apr 15 2016" "CRCL FANUC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/usr/local/michalos/github/usnistgov/el-robotics-core/nist_fanuc/include/nist_fanuc/moveit.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <vector>\fP
.br
\fC#include <boost/shared_ptr\&.hpp>\fP
.br
\fC#include <ros/ros\&.h>\fP
.br
\fC#include <moveit/move_group_interface/move_group\&.h>\fP
.br
\fC#include <moveit/planning_scene_interface/planning_scene_interface\&.h>\fP
.br
\fC#include <moveit_msgs/DisplayRobotState\&.h>\fP
.br
\fC#include <moveit_msgs/DisplayTrajectory\&.h>\fP
.br
\fC#include <moveit_msgs/AttachedCollisionObject\&.h>\fP
.br
\fC#include <moveit_msgs/CollisionObject\&.h>\fP
.br
\fC#include 'RCS\&.h'\fP
.br
\fC#include 'Globals\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMoveitPlanning\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CRCL FANUC from the source code\&.
