.TH "NIST" 3 "Fri Apr 15 2016" "CRCL FANUC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NIST \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBgetRPY\fP (const geometry_msgs::Quaternion &qmsg, double &\fBroll\fP, double &\fBpitch\fP, double &\fByaw\fP)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void NIST::getRPY (const geometry_msgs::Quaternion &qmsg, double &roll, double &pitch, double &yaw)\fC [inline]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for CRCL FANUC from the source code\&.
