.TH "/usr/local/michalos/github/usnistgov/el-robotics-core/nist_fanuc/include/nist_fanuc/Primitive.h" 3 "Fri Apr 15 2016" "CRCL FANUC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/usr/local/michalos/github/usnistgov/el-robotics-core/nist_fanuc/include/nist_fanuc/Primitive.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <ros/ros\&.h>\fP
.br
\fC#include <eigen_conversions/eigen_msg\&.h>\fP
.br
\fC#include <Eigen/src/Geometry/Transform\&.h>\fP
.br
\fC#include <geometry_msgs/Point\&.h>\fP
.br
\fC#include <geometry_msgs/Pose\&.h>\fP
.br
\fC#include <geometry_msgs/PoseStamped\&.h>\fP
.br
\fC#include <geometry_msgs/Quaternion\&.h>\fP
.br
\fC#include <moveit/move_group_interface/move_group\&.h>\fP
.br
\fC#include <moveit/planning_scene/planning_scene\&.h>\fP
.br
\fC#include <moveit/planning_scene_interface/planning_scene_interface\&.h>\fP
.br
\fC#include <moveit/robot_model/joint_model_group\&.h>\fP
.br
\fC#include <moveit/robot_model/robot_model\&.h>\fP
.br
\fC#include <moveit/robot_model_loader/robot_model_loader\&.h>\fP
.br
\fC#include <moveit/robot_state/robot_state\&.h>\fP
.br
\fC#include <moveit_msgs/CollisionObject\&.h>\fP
.br
\fC#include <moveit_msgs/DisplayTrajectory\&.h>\fP
.br
\fC#include <boost/shared_ptr\&.hpp>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCPrimitive\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CRCL FANUC from the source code\&.
