.TH "/usr/local/michalos/github/usnistgov/el-robotics-core/nist_fanuc/src/RCS.cpp" 3 "Fri Apr 15 2016" "CRCL FANUC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/usr/local/michalos/github/usnistgov/el-robotics-core/nist_fanuc/src/RCS.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'CrclConfig\&.h'\fP
.br
\fC#include 'RCS\&.h'\fP
.br
\fC#include 'Globals\&.h'\fP
.br
\fC#include 'Controller\&.h'\fP
.br
\fC#include 'crcl\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "\fBRCS\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "std::string \fBRCS::DumpPose\fP (\fBRCS::Pose\fP &pose)"
.br
.RI "\fIDumpPose takes a urdf pose and generates a string describing pose\&. Can be used as std::cout << DumpPose(pose);\&. \fP"
.ti -1c
.RI "void \fBRCS::getRPY\fP (const \fBRCS::Pose\fP pose, double &\fBroll\fP, double &\fBpitch\fP, double &\fByaw\fP)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CRCL FANUC from the source code\&.
