.TH "RCS::RobotStatus" 3 "Fri Apr 15 2016" "CRCL FANUC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RCS::RobotStatus \- 
.PP
The \fBRobotStatus\fP is a thread that reads the status of the robot and updates the world model\&. The \fBRobotStatus\fP is a separate thread that reads the robot status using ROS communication mechanisms and updates the controller world model based on these values\&. Currently, it uses an instance of the class JointReader to read joint values from the controller\&. It uses a Kinematics pointer reference to compute the current robot pose using the forward kinematics (FK) routine\&. It also uses a CrclDelegate pointer reference to update the status reported by CRCL\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Controller\&.h>\fP
.PP
Inherits \fBRCS::Thread\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRobotStatus\fP (double cycletime=\fBDEFAULT_LOOP_CYCLE\fP)"
.br
.RI "\fI\fBRobotStatus\fP constructor that requires a cycle time for \fBRCS\fP thread timing\&. \fP"
.ti -1c
.RI "\fBNVAR\fP (CrclDelegate, boost::shared_ptr< \fBCrcl::CrclDelegateInterface\fP >, _crclinterface)"
.br
.ti -1c
.RI "\fBVAR\fP (JointReader, boost::shared_ptr< \fBCJointReader\fP >)"
.br
.ti -1c
.RI "\fBVAR\fP (\fBKinematics\fP, boost::shared_ptr< \fBIKinematics\fP >)"
.br
.ti -1c
.RI "virtual int \fBAction\fP ()"
.br
.RI "\fIAction is the main loop in the \fBRCS\fP thread timing\&. Get latest robot joint readings\&. Use forward kinematics to get current pose\&. Then, updates the CRCL world model with the latest readings\&.  Should it keep track of the command id also - in theory only one CRCl command at a time\&. \fP"
.ti -1c
.RI "bool \fBVerify\fP ()"
.br
.RI "\fImethod to determine if the instance is valid, i\&.e\&., has all reference pointers\&. \fP"
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
The \fBRobotStatus\fP is a thread that reads the status of the robot and updates the world model\&. The \fBRobotStatus\fP is a separate thread that reads the robot status using ROS communication mechanisms and updates the controller world model based on these values\&. Currently, it uses an instance of the class JointReader to read joint values from the controller\&. It uses a Kinematics pointer reference to compute the current robot pose using the forward kinematics (FK) routine\&. It also uses a CrclDelegate pointer reference to update the status reported by CRCL\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "RCS::RobotStatus::RobotStatus (doublecycletime = \fC\fBDEFAULT_LOOP_CYCLE\fP\fP)"

.PP
\fBRobotStatus\fP constructor that requires a cycle time for \fBRCS\fP thread timing\&. 
.PP
\fBParameters:\fP
.RS 4
\fIcycletime\fP in seconds\&. 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "int RCS::RobotStatus::Action ()\fC [virtual]\fP"

.PP
Action is the main loop in the \fBRCS\fP thread timing\&. Get latest robot joint readings\&. Use forward kinematics to get current pose\&. Then, updates the CRCL world model with the latest readings\&.  Should it keep track of the command id also - in theory only one CRCl command at a time\&. 
.PP
Reimplemented from \fBRCS::Thread\fP\&.
.SS "RCS::RobotStatus::NVAR (CrclDelegate, boost::shared_ptr< \fBCrcl::CrclDelegateInterface\fP >, _crclinterface)"

.SS "RCS::RobotStatus::VAR (JointReader, boost::shared_ptr< \fBCJointReader\fP >)"

.SS "RCS::RobotStatus::VAR (\fBKinematics\fP, boost::shared_ptr< \fBIKinematics\fP >)"

.SS "bool RCS::RobotStatus::Verify ()\fC [inline]\fP"

.PP
method to determine if the instance is valid, i\&.e\&., has all reference pointers\&. 
.PP
\fBReturns:\fP
.RS 4
boolean to signify whether component is valid\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for CRCL FANUC from the source code\&.
