.TH "RCS::CanonCmd" 3 "Fri Apr 15 2016" "CRCL FANUC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RCS::CanonCmd \- 
.PP
\fBCanonCmd\fP is the controller command structure\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <RCS\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCanonCmd\fP ()"
.br
.RI "\fI\fBCanonCmd\fP constructor\&. \fP"
.ti -1c
.RI "void \fBInit\fP ()"
.br
.ti -1c
.RI "\fBVAR\fP (CommandID, unsigned long long)"
.br
.ti -1c
.RI "\fBVAR\fP (ParentCommandID, unsigned long long)"
.br
.ti -1c
.RI "\fBVAR\fP (StatusID, unsigned long long)"
.br
.ti -1c
.RI "\fBVAR\fP (Rates, \fBIRate\fP)"
.br
.ti -1c
.RI "bool \fBIsMotionCmd\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBCanonCmdType\fP \fBcmd\fP"
.br
.ti -1c
.RI "\fBCanonStatusType\fP \fBstatus\fP"
.br
.ti -1c
.RI "\fBTrajPointType\fP \fBtype\fP"
.br
.ti -1c
.RI "\fBCanonStopMotionType\fP \fBstoptype\fP"
.br
.ti -1c
.RI "bool \fBbCoordinated\fP"
.br
.ti -1c
.RI "bool \fBbStraight\fP"
.br
.ti -1c
.RI "double \fBabsTransAcc\fP"
.br
.ti -1c
.RI "double \fBabsTransSpeed\fP"
.br
.ti -1c
.RI "double \fBabsRotAcc\fP"
.br
.ti -1c
.RI "double \fBabsRotSpeed\fP"
.br
.ti -1c
.RI "double \fBabsJointAcc\fP"
.br
.ti -1c
.RI "double \fBabsJointSpeed\fP"
.br
.ti -1c
.RI "double \fBdwell\fP"
.br
.ti -1c
.RI "double \fBgripperPos\fP"
.br
.ti -1c
.RI "\fBCanonAccProfile\fP \fBaccprofile\fP"
.br
.ti -1c
.RI "std::vector< double > \fBspeed\fP"
.br
.ti -1c
.RI "std::vector< int > \fBjointnum\fP"
.br
.ti -1c
.RI "\fBJointState\fP \fBjoints\fP"
.br
.ti -1c
.RI "\fBJointState\fP \fBseed\fP"
.br
.ti -1c
.RI "\fBRCS::Pose\fP \fBpose\fP"
.br
.ti -1c
.RI "\fBRCS::Pose\fP \fBendPoseTol\fP"
.br
.ti -1c
.RI "std::vector< \fBRCS::Pose\fP > \fBwaypoints\fP"
.br
.ti -1c
.RI "\fBRCS::Pose\fP \fBintermediatePtTol\fP"
.br
.ti -1c
.RI "\fBRCS::Pose\fP \fBgripperTol\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static unsigned long long \fB_cmdid\fP = 0"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBCanonCmd\fP is the controller command structure\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "RCS::CanonCmd::CanonCmd ()\fC [inline]\fP"

.PP
\fBCanonCmd\fP constructor\&. 
.SH "Member Function Documentation"
.PP 
.SS "void RCS::CanonCmd::Init ()"

.SS "bool RCS::CanonCmd::IsMotionCmd ()"

.SS "RCS::CanonCmd::VAR (CommandID, unsigned longlong)"

.SS "RCS::CanonCmd::VAR (ParentCommandID, unsigned longlong)"

.SS "RCS::CanonCmd::VAR (StatusID, unsigned longlong)"

.SS "RCS::CanonCmd::VAR (Rates, \fBIRate\fP)"

.SH "Member Data Documentation"
.PP 
.SS "unsigned long long RCS::CanonCmd::_cmdid = 0\fC [static]\fP"

.SS "double RCS::CanonCmd::absJointAcc"
joint max acceleration 
.SS "double RCS::CanonCmd::absJointSpeed"
joint max velocity 
.SS "double RCS::CanonCmd::absRotAcc"
cartesian rotation acceleration 
.SS "double RCS::CanonCmd::absRotSpeed"
cartesian rotation velocity 
.SS "double RCS::CanonCmd::absTransAcc"
cartesian translational acceleration 
.SS "double RCS::CanonCmd::absTransSpeed"
cartesian translational velocity 
.SS "\fBCanonAccProfile\fP RCS::CanonCmd::accprofile"
current trajectory acceleration profile 
.SS "bool RCS::CanonCmd::bCoordinated"
coordinated joint trajectory motion boolean 
.SS "bool RCS::CanonCmd::bStraight"
straigth cartesian trajectory motion boolean 
.SS "\fBCanonCmdType\fP RCS::CanonCmd::cmd"
command type 
.SS "double RCS::CanonCmd::dwell"
time for dwelling in seconds 
.SS "\fBRCS::Pose\fP RCS::CanonCmd::endPoseTol"
commanded tolerance 
.SS "double RCS::CanonCmd::gripperPos"
gripper position 0 to 1 
.SS "\fBRCS::Pose\fP RCS::CanonCmd::gripperTol"
commanded cartesian waypoints in trajectory 
.SS "\fBRCS::Pose\fP RCS::CanonCmd::intermediatePtTol"
commanded cartesian waypoints in trajectory 
.SS "std::vector<int> RCS::CanonCmd::jointnum"
vector of joint numbers used by command 
.SS "\fBJointState\fP RCS::CanonCmd::joints"
commanded joint state 
.SS "\fBRCS::Pose\fP RCS::CanonCmd::pose"
commanded pose state 
.SS "\fBJointState\fP RCS::CanonCmd::seed"
near pose joint state 
.SS "std::vector<double> RCS::CanonCmd::speed"
vector of joint velocities 
.SS "\fBCanonStatusType\fP RCS::CanonCmd::status"
status type 
.SS "\fBCanonStopMotionType\fP RCS::CanonCmd::stoptype"
stop trajectory choice 
.SS "\fBTrajPointType\fP RCS::CanonCmd::type"
trajectory points type 
.SS "std::vector<\fBRCS::Pose\fP> RCS::CanonCmd::waypoints"
commanded cartesian waypoints in trajectory 

.SH "Author"
.PP 
Generated automatically by Doxygen for CRCL FANUC from the source code\&.
