.TH "/usr/local/michalos/github/usnistgov/el-robotics-core/nist_fanuc/include/nist_fanuc/RCSInterpreter.h" 3 "Fri Apr 15 2016" "CRCL FANUC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/usr/local/michalos/github/usnistgov/el-robotics-core/nist_fanuc/include/nist_fanuc/RCSInterpreter.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'RCS\&.h'\fP
.br
\fC#include <vector>\fP
.br
\fC#include 'Kinematics\&.h'\fP
.br
\fC#include 'Trajectory\&.h'\fP
.br
\fC#include 'trajectoryMaker\&.h'\fP
.br
\fC#include 'MotionControl\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBRCSInterpreter\fP"
.br
.RI "\fI\fBRCSInterpreter\fP parses a \fBRCS\fP command and generates robot motion commands\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CRCL FANUC from the source code\&.
