.TH "/usr/local/michalos/github/usnistgov/el-robotics-core/nist_fanuc/include/nist_fanuc/NIST/RCSMsgQueue.h" 3 "Fri Apr 15 2016" "CRCL FANUC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/usr/local/michalos/github/usnistgov/el-robotics-core/nist_fanuc/include/nist_fanuc/NIST/RCSMsgQueue.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <boost/thread/mutex\&.hpp>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBRCS::CMessageQueue< T >\fP"
.br
.RI "\fIThe \fBCMessageQueue\fP offers a mutexed front to a STL/std deque\&. The queue is a LIFO data structure\&. Useful for safely sharing data between multiple threads\&. \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "\fBRCS\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CRCL FANUC from the source code\&.
