.TH "/usr/local/michalos/github/usnistgov/el-robotics-core/nist_fanuc/include/nist_fanuc/NIST/RCSThreadTemplate.h" 3 "Fri Apr 15 2016" "CRCL FANUC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/usr/local/michalos/github/usnistgov/el-robotics-core/nist_fanuc/include/nist_fanuc/NIST/RCSThreadTemplate.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <boost/thread\&.hpp>\fP
.br
\fC#include 'RCSTimer\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBRCS::Thread\fP"
.br
.RI "\fI\fBThread\fP is an \fBRCS\fP ulapi equivalent for a timed thread\&. Given a cycle time, the thread provides a wait function to sleep to exactly the amount of the thread cycle time\&. It keeps track of busy/idle time for diagnostic purposes\&. 
.br
 Notes: https://www.quantnet.com/threads/c-multithreading-in-boost.10028/\&. \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "\fBRCS\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CRCL FANUC from the source code\&.
