.TH "/usr/local/michalos/github/usnistgov/el-robotics-core/nist_fanuc/include/nist_fanuc/RvizMarker.h" 3 "Fri Apr 15 2016" "CRCL FANUC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/usr/local/michalos/github/usnistgov/el-robotics-core/nist_fanuc/include/nist_fanuc/RvizMarker.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <ros/ros\&.h>\fP
.br
\fC#include <visualization_msgs/Marker\&.h>\fP
.br
\fC#include 'RCS\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCRvizMarker\fP"
.br
.RI "\fIThe \fBCRvizMarker\fP provides a C++ class to send markers to rviz\&. Note you must manually add the rviz subscribe to marker messages\&. Read here for explanation http://answers.ros.org/question/11135/plotting-a-markerarray-of-spheres-with-rviz/\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CRCL FANUC from the source code\&.
