
#line 3 "<stdout>"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;
#endif /* ! C99 */

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,int len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 90
#define YY_END_OF_BUFFER 91
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[629] =
    {   0,
        0,    0,    0,    0,    9,    9,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   91,   89,   89,   90,
       89,   89,   89,   18,   89,   89,   89,   89,   89,   89,
       89,   89,   89,   89,   89,   89,   89,   89,   89,   89,
       89,   89,   89,   89,    2,    3,    2,    9,    9,   11,
       14,   90,   14,   14,   90,   90,    8,    8,   90,    8,
        5,    8,   90,   90,    0,    0,    0,    0,   18,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   19,    0,    0,   20,   23,
        0,   18,   22,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    9,    0,    0,    0,    0,    0,
       16,    0,    0,    5,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,   27,
       26,    0,   21,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   40,    0,    0,   71,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    4,   10,    0,    0,    0,   15,    7,    0,
       17,    0,    0,    0,    0,    0,    0,    1,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,   74,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   48,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   53,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   33,    0,    0,    0,

        0,    0,    0,    0,    0,   68,    0,    0,    0,   39,
       69,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   45,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   52,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   61,    0,    0,    0,
        0,    0,    0,    0,    0,   37,    0,   38,    0,    0,
       72,   73,    0,    0,    0,    0,    0,    0,    0,    0,
        0,   44,    0,    0,    0,   47,    0,   83,    0,    0,
        0,    0,    0,    0,   88,    0,   54,    0,    0,    0,

        0,   29,    0,   56,    0,    0,    0,    0,    0,    0,
        0,    0,    0,   58,    0,    0,    0,    0,   65,    0,
        0,    0,   70,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,   81,    0,    0,    0,    0,    0,    0,
        0,   50,    0,    0,    0,    0,    0,   12,    0,    0,
        6,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       34,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   84,   85,
        0,    0,    0,    0,    0,   55,    0,    0,   28,    0,
        0,    0,    0,   31,    0,   59,    0,    0,    0,    0,

        0,   36,    0,   67,    0,   41,    0,    0,   77,    0,
        0,    0,   80,    0,    0,   46,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   57,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   42,    0,    0,
        0,   43,    0,    0,    0,   87,    0,    0,    0,    0,
        0,    0,    0,    0,   63,    0,    0,   66,    0,    0,
        0,    0,   82,    0,    0,    0,    0,    0,    0,   25,
        0,    0,    0,    0,    0,   75,   76,   78,   79,    0,
        0,    0,    0,    0,   24,    0,    0,    0,    0,   64,
        0,    0,   86,    0,    0,   13,    0,   60,   62,    0,

        0,    0,    0,    0,    0,    0,   49,    0,    0,    0,
        0,    0,    0,   30,    0,    0,    0,    0,    0,    0,
       51,    0,    0,   35,    0,    0,   32,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    5,    6,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    7,    1,    8,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    9,    1,   10,
       11,   12,   13,    1,   14,   14,   15,   16,   17,   18,
       19,   14,   20,   14,   14,   21,   14,   22,   23,   14,
       14,   14,   14,   24,   14,   14,   14,   14,   14,   14,
        1,    1,    1,    1,    1,    1,   25,   26,   27,   28,

       29,   30,   31,   32,   33,   14,   34,   35,   36,   37,
       38,   39,   40,   41,   42,   43,   44,   45,   14,   46,
       47,   14,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[48] =
    {   0,
        1,    1,    1,    1,    2,    3,    1,    2,    4,    5,
        1,    1,    2,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6
    } ;

static yyconst flex_int16_t yy_base[645] =
    {   0,
        0,    0,   45,   46,   47,   48,   51,   52,  965,  964,
      963,  962,   57,   62,   69,   79,  967,  972,  103,    0,
        0,  954,   79,   87,  953,   71,  939,   24,   57,   66,
       60,  922,   98,  933,   67,   45,   69,  936,  931,  123,
       95,   80,   94,   82,  972,  972,  952,    0,    0,  950,
      972,  972,  918,  918,    0,  949,  972,  151,  156,    0,
      972,  916,  167,    0,    0,    0,  941,  167,  162,  940,
      108,  926,  921,   90,  105,  146,  152,  153,  920,  152,
      156,  906,  158,  152,  186,  972,  940,  937,  920,  972,
      192,  204,  972,  902,  906,  903,  898,  898,  901,  902,

      907,  909,  906,  155,  891,  165,  892,  894,  210,  904,
      901,  882,  891,  885,  880,  172,  889,  889,  880,  174,
      890,  175,  885,  876,  893,  877,  878,  883,  886,  879,
      872,  877,  886,  898,    0,  900,  869,  880,  900,  899,
      972,  220,    0,  972,  866,  897,  858,  225,    0,  895,
      857,  870,  871,  188,  851,  193,  866,  863,  859,  972,
      972,  886,  972,  883,  854,  847,  851,  855,  846,  857,
      852,  845,  858,  838,  845,  842,  843,  849,  842,  851,
      846,  838,  829,  233,  972,  837,  835,  829,  838,  825,
      225,  230,  838,  837,  830,  821,  252,  820,  833,  832,

      816,  820,  817,  815,  825,  826,  814,  255,  809,  810,
      182,  808,  972,  972,  841,  816,  804,  972,  972,  806,
      972,  805,  809,  821,  820,  813,  804,  972,  803,  798,
      795,  800,  803,  265,  808,  799,  789,  796,  802,  802,
      800,  791,  799,  791,  797,  268,  785,  779,  798,  792,
      777,  972,  773,  781,  788,  789,  769,  777,  784,  785,
      783,  271,  785,  780,  281,  972,  767,  766,  770,  778,
      775,  768,  775,  758,  771,  284,  755,  287,  972,  769,
      764,  215,  754,  763,  757,  757,  765,  758,  761,  753,
      750,  762,  761,  755,  758,  297,  972,  754,  753,  746,

      751,  742,  745,  736,  734,  972,  300,  303,  313,  972,
      972,  747,  727,  743,  740,  744,  743,  732,  741,  740,
      739,  728,  737,  316,  319,  972,  737,  721,  329,  728,
      735,  716,  721,  728,  727,  722,  711,  332,  972,  724,
      335,  714,  722,  345,  348,  720,  720,  719,  721,  709,
      720,  701,  716,  699,  703,  696,  972,  693,  695,  700,
      693,  698,  709,  700,  358,  972,  361,  972,  703,  692,
      972,  972,  695,  694,  697,  683,  691,  690,  693,  679,
      364,  972,  687,  684,  374,  972,  693,  698,  680,  690,
      225,  377,  673,  693,  972,  380,  972,  677,  672,  390,

        0,  972,  393,  972,  674,  674,  396,  666,  666,  687,
      682,  663,  672,  972,  661,  228,  406,  660,  684,  670,
      657,  661,  972,  669,  653,  652,  652,  653,  649,  648,
      648,  649,  660,  972,  645,  649,  645,  656,  646,  636,
      409,  972,  638,  656,  412,  638,  422,  972,  636,  425,
      972,  635,  659,  633,  428,  637,  645,  635,  625,  438,
      972,  646,  632,  441,  636,  631,  444,  625,  624,  633,
      622,  620,  617,  622,  606,  454,  603,  605,  972,  972,
      589,  585,  577,  583,  457,  972,  546,  460,  972,  553,
      547,  542,  470,  972,  537,  246,  529,  526,  520,  521,

      473,  972,  512,  972,  476,  972,  516,  514,  972,  486,
      513,  501,  972,  489,  492,  972,  495,  506,  487,  489,
      484,  486,  476,  459,  483,  461,  972,  460,  445,  442,
      454,  449,  434,  432,  422,  421,  502,  972,  409,  408,
      505,  972,  414,  407,  409,  972,  399,  393,  397,  389,
      384,  378,  380,  377,  972,  367,  387,  972,  373,  361,
      360,  358,  972,  353,  337,  336,  332,  508,  332,  972,
      322,  313,  318,  316,  316,  972,  972,  972,  972,  306,
      299,  322,  304,  518,  972,  291,  310,  286,  270,  972,
      282,  273,  972,  268,  270,  972,  267,  972,  972,  269,

      521,  255,  251,  248,  233,  524,  972,  217,  534,  216,
      203,  194,  537,  972,  176,   94,  540,   95,  550,  553,
      972,   81,  556,  972,  566,  569,  972,  972,  580,  586,
      592,  598,  604,  610,  616,  621,  627,  633,  639,  645,
      651,  654,  657,   61
    } ;

static yyconst flex_int16_t yy_def[645] =
    {   0,
      628,    1,  629,  629,  630,  630,  631,  631,  632,  632,
      633,  633,  634,  634,  632,  632,  628,  628,  628,   19,
      635,  628,  636,  628,  628,  628,  628,  628,  628,  628,
      628,  628,  628,  628,  628,  628,  628,  628,  628,  628,
      628,  628,  628,  628,  628,  628,  628,  637,  637,  628,
      628,  628,  628,  628,  638,  639,  628,  628,  628,  640,
      628,  628,  628,  641,   19,  635,  628,  636,  628,  628,
      628,  628,  628,  628,  628,  628,  628,  628,  628,  628,
      628,  628,  628,  628,  635,  628,  628,  642,  628,  628,
      636,  628,  628,  628,  628,  628,  628,  628,  628,  628,

      628,  628,  628,  628,  628,  628,  628,  628,  628,  628,
      628,  628,  628,  628,  628,  628,  628,  628,  628,  628,
      628,  628,  628,  628,  628,  628,  628,  628,  628,  628,
      628,  628,  628,  628,  637,  643,  628,  628,  638,  639,
      628,  628,  640,  628,  628,  640,  628,  628,  641,  641,
      628,  628,  628,  628,  628,  628,  628,  628,  628,  628,
      628,  628,  628,  642,  628,  628,  628,  628,  628,  628,
      628,  628,  628,  628,  628,  628,  628,  628,  628,  628,
      628,  628,  628,  628,  628,  628,  628,  628,  628,  628,
      628,  628,  628,  628,  628,  628,  628,  628,  628,  628,

      628,  628,  628,  628,  628,  628,  628,  628,  628,  628,
      628,  628,  628,  628,  643,  628,  628,  628,  628,  628,
      628,  628,  628,  628,  628,  628,  628,  628,  628,  628,
      628,  628,  628,  628,  628,  628,  628,  628,  628,  628,
      628,  628,  628,  628,  628,  628,  628,  628,  628,  628,
      628,  628,  628,  628,  628,  628,  628,  628,  628,  628,
      628,  628,  628,  628,  628,  628,  628,  628,  628,  628,
      628,  628,  628,  628,  628,  628,  628,  628,  628,  628,
      628,  628,  628,  628,  628,  628,  628,  628,  628,  628,
      628,  628,  628,  628,  628,  628,  628,  628,  628,  628,

      628,  628,  628,  628,  628,  628,  628,  628,  628,  628,
      628,  628,  628,  628,  628,  628,  628,  628,  628,  628,
      628,  628,  628,  628,  628,  628,  628,  628,  628,  628,
      628,  628,  628,  628,  628,  628,  628,  628,  628,  628,
      628,  628,  628,  628,  628,  628,  628,  628,  628,  628,
      628,  628,  628,  628,  628,  628,  628,  628,  628,  628,
      628,  628,  628,  628,  628,  628,  628,  628,  628,  628,
      628,  628,  628,  628,  628,  628,  628,  628,  628,  628,
      628,  628,  628,  628,  628,  628,  628,  628,  628,  628,
      628,  628,  628,  628,  628,  628,  628,  628,  628,  628,

      644,  628,  628,  628,  628,  628,  628,  628,  628,  628,
      628,  628,  628,  628,  628,  628,  628,  628,  628,  628,
      628,  628,  628,  628,  628,  628,  628,  628,  628,  628,
      628,  628,  628,  628,  628,  628,  628,  628,  628,  628,
      628,  628,  628,  628,  628,  628,  644,  628,  628,  628,
      628,  628,  628,  628,  628,  628,  628,  628,  628,  628,
      628,  628,  628,  628,  628,  628,  628,  628,  628,  628,
      628,  628,  628,  628,  628,  628,  628,  628,  628,  628,
      628,  628,  628,  628,  628,  628,  628,  628,  628,  628,
      628,  628,  628,  628,  628,  628,  628,  628,  628,  628,

      628,  628,  628,  628,  628,  628,  628,  628,  628,  628,
      628,  628,  628,  628,  628,  628,  628,  628,  628,  628,
      628,  628,  628,  628,  628,  628,  628,  628,  628,  628,
      628,  628,  628,  628,  628,  628,  628,  628,  628,  628,
      628,  628,  628,  628,  628,  628,  628,  628,  628,  628,
      628,  628,  628,  628,  628,  628,  628,  628,  628,  628,
      628,  628,  628,  628,  628,  628,  628,  628,  628,  628,
      628,  628,  628,  628,  628,  628,  628,  628,  628,  628,
      628,  628,  628,  628,  628,  628,  628,  628,  628,  628,
      628,  628,  628,  628,  628,  628,  628,  628,  628,  628,

      628,  628,  628,  628,  628,  628,  628,  628,  628,  628,
      628,  628,  628,  628,  628,  628,  628,  628,  628,  628,
      628,  628,  628,  628,  628,  628,  628,    0,  628,  628,
      628,  628,  628,  628,  628,  628,  628,  628,  628,  628,
      628,  628,  628,  628
    } ;

static yyconst flex_int16_t yy_nxt[1020] =
    {   0,
       18,   19,   20,   19,   18,   21,   18,   22,   18,   23,
       18,   24,   25,   18,   18,   18,   18,   18,   18,   18,
       18,   18,   18,   18,   26,   27,   28,   29,   30,   31,
       32,   18,   33,   34,   35,   36,   37,   18,   38,   18,
       39,   40,   41,   42,   43,   44,   18,   46,   46,   49,
       49,   47,   47,   52,   52,   99,   50,   50,   58,   59,
       58,  100,   60,   58,   59,   58,  447,   60,   61,  115,
       63,   63,   63,   61,   64,   53,   53,  116,   54,   54,
       63,   63,   63,   87,   64,  101,   88,   89,   92,   92,
       92,   90,  106,  117,  102,  113,   94,  107,   62,  114,

      103,  118,  104,   62,   65,   65,   65,   95,   66,   96,
       67,  105,   68,   97,   69,   70,  128,  132,  130,  126,
      133,  129,  131,  625,  152,  109,  153,   71,   72,  622,
       73,   74,   75,   94,  110,   76,  619,  154,   77,   78,
      111,  127,  107,   79,   80,   81,   82,   83,   84,  121,
      151,  122,  142,  142,  142,  123,  143,  142,  142,  142,
      124,  143,  144,   92,   92,   92,  125,  144,  148,  148,
      148,   87,  149,  109,   88,   89,  155,  117,  158,   90,
      126,  176,  130,  282,  156,  118,  131,  159,  111,  124,
      133,  160,  145,  179,  161,  125,  628,  145,  177,  628,

       89,  180,  127,  197,  628,   92,   92,   92,  192,  200,
      181,  184,  184,  184,  201,  198,  282,  193,  283,  618,
      185,  142,  142,  142,  180,  143,  148,  148,  148,  225,
      149,  144,  617,  181,  184,  184,  184,  616,  193,  439,
      615,  253,  458,  185,  254,  255,  257,  256,  440,  258,
      259,  459,  260,  265,  265,  265,  278,  278,  278,  343,
      612,  145,  266,  528,  529,  279,  296,  296,  296,  309,
      309,  309,  325,  325,  325,  297,  611,  610,  310,  609,
      267,  326,  265,  265,  265,  338,  338,  338,  278,  278,
      278,  266,  608,  605,  339,  604,  603,  279,  296,  296,

      296,  365,  365,  365,  367,  367,  367,  297,  602,  601,
      366,  600,  599,  368,  309,  309,  309,  381,  381,  381,
      325,  325,  325,  310,  598,  597,  382,  596,  595,  326,
      385,  385,  385,  338,  338,  338,  396,  396,  396,  386,
      594,  593,  339,  592,  591,  397,  400,  400,  400,  403,
      403,  403,  590,  401,  589,  402,  588,  587,  404,  365,
      365,  365,  367,  367,  367,  381,  381,  381,  366,  586,
      583,  368,  582,  581,  382,  385,  385,  385,  441,  441,
      441,  396,  396,  396,  386,  580,  579,  442,  578,  577,
      397,  400,  400,  400,  403,  403,  403,  450,  450,  450,

      402,  576,  575,  404,  574,  573,  451,  460,  460,  460,
      441,  441,  441,  485,  485,  485,  461,  572,  571,  442,
      570,  569,  486,  488,  488,  488,  450,  450,  450,  493,
      493,  493,  489,  568,  567,  451,  566,  565,  494,  460,
      460,  460,  501,  501,  501,  505,  505,  505,  461,  564,
      563,  502,  562,  561,  506,  515,  515,  515,  485,  485,
      485,  488,  488,  488,  516,  560,  559,  486,  558,  557,
      489,  493,  493,  493,  501,  501,  501,  505,  505,  505,
      494,  556,  555,  502,  554,  553,  506,  537,  537,  537,
      541,  541,  541,  515,  515,  515,  538,  552,  551,  542,

      528,  550,  516,  537,  537,  537,  541,  541,  541,  584,
      584,  584,  538,  549,  548,  542,  547,  546,  585,  584,
      584,  584,  606,  606,  606,  606,  606,  606,  585,  545,
      544,  607,  543,  540,  607,  613,  613,  613,  613,  613,
      613,  620,  620,  620,  614,  539,  536,  614,  535,  534,
      621,  623,  623,  623,  620,  620,  620,  623,  623,  623,
      624,  533,  532,  621,  531,  530,  624,  626,  626,  626,
      626,  626,  626,  527,  526,  525,  627,  524,  523,  627,
       45,   45,   45,   45,   45,   45,   48,   48,   48,   48,
       48,   48,   51,   51,   51,   51,   51,   51,   52,   52,

       52,   52,   52,   52,   56,   56,   56,   56,   56,   56,
       57,   57,   57,   57,   57,   57,   85,   85,  522,  521,
       85,   85,   91,  520,   91,  519,   91,  135,  135,  135,
      135,  518,  135,  139,  139,  517,  139,  139,  139,  140,
      140,  140,  140,  140,  140,  146,  146,  514,  146,  146,
      146,  150,  150,  513,  150,  150,  150,  164,  512,  164,
      215,  511,  215,  510,  509,  508,  507,  504,  503,  500,
      499,  498,  497,  496,  495,  492,  463,  491,  490,  487,
      484,  483,  482,  481,  480,  479,  478,  477,  476,  475,
      474,  473,  472,  471,  470,  469,  468,  467,  466,  465,

      464,  463,  462,  457,  456,  455,  454,  436,  453,  452,
      449,  448,  446,  445,  444,  443,  438,  437,  436,  435,
      434,  433,  432,  431,  430,  429,  428,  427,  426,  425,
      424,  423,  422,  421,  420,  419,  418,  417,  416,  415,
      414,  413,  412,  411,  410,  409,  408,  407,  406,  405,
      399,  398,  395,  394,  393,  392,  391,  390,  389,  388,
      387,  384,  383,  380,  379,  378,  377,  376,  375,  374,
      373,  372,  371,  370,  369,  364,  363,  362,  361,  360,
      359,  358,  357,  356,  355,  354,  353,  352,  351,  350,
      349,  348,  347,  346,  345,  344,  342,  341,  340,  337,

      336,  335,  334,  333,  332,  331,  330,  329,  328,  327,
      324,  323,  322,  321,  320,  319,  318,  317,  316,  315,
      314,  313,  312,  311,  308,  307,  306,  305,  304,  303,
      302,  301,  300,  299,  298,  295,  294,  293,  292,  291,
      283,  290,  260,  256,  289,  288,  287,  286,  285,  214,
      284,  281,  280,  277,  276,  275,  274,  273,  272,  271,
      270,  269,  268,  264,  263,  262,  261,  252,  251,  250,
      249,  248,  247,  246,  245,  244,  243,  242,  241,  240,
      239,  238,  237,  236,  235,  234,  233,  232,  231,  230,
      229,  163,  228,  227,  226,  197,  224,  176,  223,  222,

      221,  220,  219,  147,  141,  218,  217,  216,  214,  213,
      212,  211,  210,  209,  208,  207,  206,  205,  204,  203,
      202,  199,  196,  195,  194,  191,  190,  189,  188,  187,
      186,  183,  182,  178,  175,  174,  173,  172,  171,  170,
      169,  168,  167,  166,  165,  163,  162,  129,  157,  101,
       98,   93,   86,  147,  141,  138,  137,  136,  134,  120,
      119,  112,  108,   98,   93,   86,  628,   52,   52,   55,
       55,   17,  628,  628,  628,  628,  628,  628,  628,  628,
      628,  628,  628,  628,  628,  628,  628,  628,  628,  628,
      628,  628,  628,  628,  628,  628,  628,  628,  628,  628,

      628,  628,  628,  628,  628,  628,  628,  628,  628,  628,
      628,  628,  628,  628,  628,  628,  628,  628,  628
    } ;

static yyconst flex_int16_t yy_chk[1020] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    3,    4,    5,
        6,    3,    4,    7,    8,   28,    5,    6,   13,   13,
       13,   28,   13,   14,   14,   14,  644,   14,   13,   36,
       15,   15,   15,   14,   15,    7,    8,   36,    7,    8,
       16,   16,   16,   23,   16,   29,   23,   23,   24,   24,
       24,   23,   31,   37,   29,   35,   26,   31,   13,   35,

       30,   37,   30,   14,   19,   19,   19,   26,   19,   26,
       19,   30,   19,   26,   19,   19,   42,   44,   43,   41,
       44,   42,   43,  622,   74,   33,   74,   19,   19,  618,
       19,   19,   19,   71,   33,   19,  616,   75,   19,   19,
       33,   41,   75,   19,   19,   19,   19,   19,   19,   40,
       71,   40,   58,   58,   58,   40,   58,   59,   59,   59,
       40,   59,   58,   69,   69,   69,   40,   59,   63,   63,
       63,   68,   63,   76,   68,   68,   77,   78,   80,   68,
       81,  104,   83,  211,   77,   78,   83,   84,   76,   80,
       84,   85,   58,  106,   85,   80,   91,   59,  104,   91,

       91,  106,   81,  120,   91,   92,   92,   92,  116,  122,
      106,  109,  109,  109,  122,  120,  282,  116,  211,  615,
      109,  142,  142,  142,  154,  142,  148,  148,  148,  156,
      148,  142,  612,  154,  184,  184,  184,  611,  156,  391,
      610,  191,  416,  184,  191,  191,  192,  191,  391,  192,
      192,  416,  192,  197,  197,  197,  208,  208,  208,  282,
      608,  142,  197,  496,  496,  208,  234,  234,  234,  246,
      246,  246,  262,  262,  262,  234,  605,  604,  246,  603,
      197,  262,  265,  265,  265,  276,  276,  276,  278,  278,
      278,  265,  602,  600,  276,  597,  595,  278,  296,  296,

      296,  307,  307,  307,  308,  308,  308,  296,  594,  592,
      307,  591,  589,  308,  309,  309,  309,  324,  324,  324,
      325,  325,  325,  309,  588,  587,  324,  586,  583,  325,
      329,  329,  329,  338,  338,  338,  341,  341,  341,  329,
      582,  581,  338,  580,  575,  341,  344,  344,  344,  345,
      345,  345,  574,  344,  573,  344,  572,  571,  345,  365,
      365,  365,  367,  367,  367,  381,  381,  381,  365,  569,
      567,  367,  566,  565,  381,  385,  385,  385,  392,  392,
      392,  396,  396,  396,  385,  564,  562,  392,  561,  560,
      396,  400,  400,  400,  403,  403,  403,  407,  407,  407,

      400,  559,  557,  403,  556,  554,  407,  417,  417,  417,
      441,  441,  441,  445,  445,  445,  417,  553,  552,  441,
      551,  550,  445,  447,  447,  447,  450,  450,  450,  455,
      455,  455,  447,  549,  548,  450,  547,  545,  455,  460,
      460,  460,  464,  464,  464,  467,  467,  467,  460,  544,
      543,  464,  540,  539,  467,  476,  476,  476,  485,  485,
      485,  488,  488,  488,  476,  536,  535,  485,  534,  533,
      488,  493,  493,  493,  501,  501,  501,  505,  505,  505,
      493,  532,  531,  501,  530,  529,  505,  510,  510,  510,
      514,  514,  514,  515,  515,  515,  510,  528,  526,  514,

      525,  524,  515,  537,  537,  537,  541,  541,  541,  568,
      568,  568,  537,  523,  522,  541,  521,  520,  568,  584,
      584,  584,  601,  601,  601,  606,  606,  606,  584,  519,
      518,  601,  517,  512,  606,  609,  609,  609,  613,  613,
      613,  617,  617,  617,  609,  511,  508,  613,  507,  503,
      617,  619,  619,  619,  620,  620,  620,  623,  623,  623,
      619,  500,  499,  620,  498,  497,  623,  625,  625,  625,
      626,  626,  626,  495,  492,  491,  625,  490,  487,  626,
      629,  629,  629,  629,  629,  629,  630,  630,  630,  630,
      630,  630,  631,  631,  631,  631,  631,  631,  632,  632,

      632,  632,  632,  632,  633,  633,  633,  633,  633,  633,
      634,  634,  634,  634,  634,  634,  635,  635,  484,  483,
      635,  635,  636,  482,  636,  481,  636,  637,  637,  637,
      637,  478,  637,  638,  638,  477,  638,  638,  638,  639,
      639,  639,  639,  639,  639,  640,  640,  475,  640,  640,
      640,  641,  641,  474,  641,  641,  641,  642,  473,  642,
      643,  472,  643,  471,  470,  469,  468,  466,  465,  463,
      462,  459,  458,  457,  456,  454,  453,  452,  449,  446,
      444,  443,  440,  439,  438,  437,  436,  435,  433,  432,
      431,  430,  429,  428,  427,  426,  425,  424,  422,  421,

      420,  419,  418,  415,  413,  412,  411,  410,  409,  408,
      406,  405,  399,  398,  394,  393,  390,  389,  388,  387,
      384,  383,  380,  379,  378,  377,  376,  375,  374,  373,
      370,  369,  364,  363,  362,  361,  360,  359,  358,  356,
      355,  354,  353,  352,  351,  350,  349,  348,  347,  346,
      343,  342,  340,  337,  336,  335,  334,  333,  332,  331,
      330,  328,  327,  323,  322,  321,  320,  319,  318,  317,
      316,  315,  314,  313,  312,  305,  304,  303,  302,  301,
      300,  299,  298,  295,  294,  293,  292,  291,  290,  289,
      288,  287,  286,  285,  284,  283,  281,  280,  277,  275,

      274,  273,  272,  271,  270,  269,  268,  267,  264,  263,
      261,  260,  259,  258,  257,  256,  255,  254,  253,  251,
      250,  249,  248,  247,  245,  244,  243,  242,  241,  240,
      239,  238,  237,  236,  235,  233,  232,  231,  230,  229,
      227,  226,  225,  224,  223,  222,  220,  217,  216,  215,
      212,  210,  209,  207,  206,  205,  204,  203,  202,  201,
      200,  199,  198,  196,  195,  194,  193,  190,  189,  188,
      187,  186,  183,  182,  181,  180,  179,  178,  177,  176,
      175,  174,  173,  172,  171,  170,  169,  168,  167,  166,
      165,  164,  162,  159,  158,  157,  155,  153,  152,  151,

      150,  147,  146,  145,  140,  139,  138,  137,  136,  134,
      133,  132,  131,  130,  129,  128,  127,  126,  125,  124,
      123,  121,  119,  118,  117,  115,  114,  113,  112,  111,
      110,  108,  107,  105,  103,  102,  101,  100,   99,   98,
       97,   96,   95,   94,   89,   88,   87,   82,   79,   73,
       72,   70,   67,   62,   56,   54,   53,   50,   47,   39,
       38,   34,   32,   27,   25,   22,   17,   12,   11,   10,
        9,  628,  628,  628,  628,  628,  628,  628,  628,  628,
      628,  628,  628,  628,  628,  628,  628,  628,  628,  628,
      628,  628,  628,  628,  628,  628,  628,  628,  628,  628,

      628,  628,  628,  628,  628,  628,  628,  628,  628,  628,
      628,  628,  628,  628,  628,  628,  628,  628,  628
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;

/******************************************************************************
  DISCLAIMER:
  This software was produced by the National Institute of Standards
  and Technology (NIST), an agency of the U.S. government, and by statute is
  not subject to copyright in the United States.  Recipients of this software
  assume all responsibility associated with its operation, modification,
  maintenance, and subsequent redistribution.

  See NIST Administration Manual 4.09.07 b and Appendix I. 
*****************************************************************************/

/*

This expects that the XmlCppBase::wg3Prefix will be 0 before the
first thing of the form "<xs:" is seen, where "xs" could be any alphabetic
characters.  The first time something of that form is seen, this sets
XmlCppBase::wg3Prefix to the string consisting of the characters that
were found. Every other time < is seen followed by some alphabetic
characters and a colon, this checks that the characters are the same
as XmlCppBase::wg3Prefix. If the check fails, this records an error
message and returns BAD.

In general, this looks for preceding white space and not trailing
white space. The one exception to this is for ENDITEM, which allows
both preceding and trailing white space. This is done because DOS
files cause the parser to fail at the very end of the file if trailing
white space is not allowed.

A prefix is some letters preceding or following a colon. Let XXX stand
for a prefix. The prefixes in <XXX: and </XXX: are handled by
doPrefix.  The prefix in xmlns:XXX= is pulled out and returned as the
value of XMLNSPREFIX. The string following targetNamespace= or
xmlns:XXX= will probably have a colon in it, but we do not want to
treat the part before or after the colon as a prefix, so strings following
targetNamespace= and xmlns:XXX= are handled by going into the STRING
mode. Other prefixes, which occur mainly in type names, are handled by
returning the prefix as the value of XMLNSPREFIX and going into the
PREFIXED mode.

The value of a pattern or an enumeration may include a colon, so an
inPatEnum variable and a PATENUMVALUE state are defined. The inPatEnum
is set to 1 when a pattern or an enumeration is found, and the
PATENUMVALUE state is entered if "value" is read and inPatEnum is 1.

*/

#include <string.h>            // for strdup
#include "xmlSchemaClasses.hh" // for classes referenced in xmlSchemaYACC.hh
#include "xmlSchemaYACC.hh"    // for tokens, yylval, etc.

#define ECHO_IT 1
#define ECH if (ECHO_IT) ECHO

extern char lexMessage[];
extern char commentString[];

int n;
int first;
char lexbuf[40];
int inPatEnum = 0;

/********************************************************************/

/* doPrefix

Returned Value: int
  This returns the retVal argument.

Called By: The lex lines that read prefixes preceded by < or </

The value of the tex argument is something like <xs: or </xs:
where the xs (or xsd or whatever) is the prefix we are after.
The function removes everything before the x and deletes the
colon at the end.

The first time this is called is when the second line of the
schema file is being read. That line reads: <xs:schema ...
where the xs may be xsd or anything else; in any event, it
is what the XmlCppBase::wg3Prefix should be. XmlCppBase::wg3Prefix
is zero at that time, so this sets it to a copy of the prefix.

Every other time this is called, it checks that the prefix is
the same as XmlCppBase::wg3Prefix.

*/

int doPrefix( /* ARGUMENTS                */
 char * tex,  /* string containing prefix */
 int retVal)  /* value to return          */
{
  int first;

  tex[strlen(tex) - 1] = 0; // delete the colon at the end
  for (first = 0; tex[first] < 'A'; first++); // skip <, /, and white space
  if (XmlCppBase::wg3Prefix == 0)
    XmlCppBase::wg3Prefix = strdup(tex + first);
  else if (strcmp((tex + first), XmlCppBase::wg3Prefix))
    {
      sprintf(lexMessage, "Bad prefix %s. Prefix should be %s\n",
	      (tex + first), XmlCppBase::wg3Prefix);
      return BAD;
    }
  return retVal;
}

/********************************************************************/

#define INITIAL 0
#define COMMENT 1
#define DOC 2
#define ENDDOC 3
#define PATENUMVALUE 4
#define PREFIXED 5
#define STARTDOC 6
#define STRING 7

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

int yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		unsigned n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 629 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 972 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
{ ECH; /* no need to save <!-- */
                             n = 0;
                             BEGIN(COMMENT);
                             return STARTCOMMENT;
                           }
	YY_BREAK
case 2:
YY_RULE_SETUP
{ ECH;
                             commentString[n++] = yytext[0];
			     if (n >= 40000)
                               { strcpy(lexMessage, "comment too long");
				 return BAD;
			       }
                           }
	YY_BREAK
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
{ ECH;
                             commentString[n++] = yytext[0];
			     if (n >= 40000)
                               { strcpy(lexMessage, "comment too long");
				 return BAD;
			       }
                           }
	YY_BREAK
case 4:
YY_RULE_SETUP
{ ECH; /* no need to save --> */
                             commentString[n] = 0;
                             BEGIN(INITIAL);
                             return ENDCOMMENT;
                           }
	YY_BREAK
case 5:
/* rule 5 can match eol */
YY_RULE_SETUP
{ ECH; BEGIN(DOC); return ENDITEM; }
	YY_BREAK
case 6:
/* rule 6 can match eol */
YY_RULE_SETUP
{ ECH; return SOURCE; }
	YY_BREAK
case 7:
/* rule 7 can match eol */
YY_RULE_SETUP
{ ECH;
                             for (first = 0; yytext[first] != '"'; first++);
                             first++;
 			     for (n = first; yytext[n] != '"'; n++);
 			     yytext[n] = 0;
                             yylval.sVal = strdup(yytext + first);
			     return TERMINALSTRING;
                           }
	YY_BREAK
case 8:
YY_RULE_SETUP
{ ECH; return BAD; }
	YY_BREAK
case 9:
/* rule 9 can match eol */
YY_RULE_SETUP
{ ECH;
                             yylval.sVal = strdup(yytext);
			     return TERMINALSTRING;
                           }
	YY_BREAK
case 10:
YY_RULE_SETUP
{ ECH; BEGIN(ENDDOC);
                             return doPrefix(yytext, STARTOUTITEM);
                           }
	YY_BREAK
case 11:
YY_RULE_SETUP
{ ECH; return BAD; }
	YY_BREAK
case 12:
YY_RULE_SETUP
{ ECH; BEGIN(INITIAL); return XSAPPINFO; }
	YY_BREAK
case 13:
YY_RULE_SETUP
{ ECH; BEGIN(INITIAL); return XSDOCUMENTATION; }
	YY_BREAK
case 14:
YY_RULE_SETUP
{ ECH; return BAD; }
	YY_BREAK
case 15:
/* rule 15 can match eol */
YY_RULE_SETUP
{ ECH; 
                             for (first = 0; yytext[first] != '"'; first++);
                             first++;
 			     for (n = first; yytext[n] != '"'; n++);
 			     yytext[n] = 0;
                             yylval.sVal = strdup(yytext + first);
                             inPatEnum = 0;
                             BEGIN(INITIAL);
			     return TERMINALSTRING;
                           }
	YY_BREAK
case 16:
/* rule 16 can match eol */
YY_RULE_SETUP
{ ECH;
                             for (n = 0; yytext[n] != '"'; n++);
 			     yytext[n] = 0;
                             yylval.sVal = strdup(yytext);
                             BEGIN(INITIAL);
			     return TERMINALSTRING;
                           }
	YY_BREAK
case 17:
/* rule 17 can match eol */
YY_RULE_SETUP
{ ECH;
                             for (first = 0; yytext[first] != '"'; first++);
                             first++;
 			     for (n = first; yytext[n] != '"'; n++);
 			     yytext[n] = 0;
                             yylval.sVal = strdup(yytext + first);
                             BEGIN(INITIAL);
			     return TERMINALSTRING;
                           }
	YY_BREAK
case 18:
/* rule 18 can match eol */
YY_RULE_SETUP
{ ECH; return ENDITEM; }
	YY_BREAK
case 19:
/* rule 19 can match eol */
YY_RULE_SETUP
{ ECH; return ENDWHOLEITEM; }
	YY_BREAK
case 20:
/* rule 20 can match eol */
YY_RULE_SETUP
{ ECH; return doPrefix(yytext, STARTINITEM);}
	YY_BREAK
case 21:
/* rule 21 can match eol */
YY_RULE_SETUP
{ ECH; return doPrefix(yytext, STARTOUTITEM);}
	YY_BREAK
case 22:
/* rule 22 can match eol */
YY_RULE_SETUP
{ ECH; return ENDVERSION; }
	YY_BREAK
case 23:
/* rule 23 can match eol */
YY_RULE_SETUP
{ ECH; return STARTVERSION; }
	YY_BREAK
case 24:
/* rule 24 can match eol */
YY_RULE_SETUP
{ ECH; return XMLVERSION; }
	YY_BREAK
case 25:
/* rule 25 can match eol */
YY_RULE_SETUP
{ ECH;
                               for (n = 0; yytext[n] != ':'; n++);
                               yytext[n+1] = 0;
                               return doPrefix(yytext, STARTANNOTATION);
                             }
	YY_BREAK
case 26:
/* rule 26 can match eol */
YY_RULE_SETUP
{ ECH;
                             for (first = 0; yytext[first] != '"'; first++);
                             first++;
 			     for (n = first; yytext[n] != ':'; n++);
 			     yytext[n] = 0;
                             yylval.sVal = strdup(yytext + first);
                             BEGIN(PREFIXED);
                             return XMLNSPREFIX;
                           }
	YY_BREAK
case 27:
/* rule 27 can match eol */
YY_RULE_SETUP
{ ECH;
                             for (first = 0; yytext[first] != '"'; first++);
                             first++;
 			     for (n = first; yytext[n] != '"'; n++);
 			     yytext[n] = 0;
                             yylval.sVal = strdup(yytext + first);
			     return TERMINALSTRING;
                           }
	YY_BREAK
case 28:
/* rule 28 can match eol */
YY_RULE_SETUP
{ ECH;
                             for (first = 0; yytext[first] != ':'; first++);
                             first++;
			     for (n = first;
				  (((yytext[n] >= 'A') && (yytext[n] <= 'Z')) ||
				   ((yytext[n] >= 'a') && (yytext[n] <= 'z')));
				  n++);
			     yytext[n] = 0;
			     yylval.sVal = strdup(yytext + first);
                             BEGIN(STRING);
			     return XMLNSPREFIX;
		           }
	YY_BREAK
case 29:
/* rule 29 can match eol */
YY_RULE_SETUP
{ ECH;
			     yylval.sVal = 0;
                             BEGIN(STRING);
			     return XMLNSPREFIX;
		           }
	YY_BREAK
case 30:
/* rule 30 can match eol */
YY_RULE_SETUP
{ ECH;
                             BEGIN(STRING);
                             return TARGETNAMESPACE;
                           }
	YY_BREAK
case 31:
/* rule 31 can match eol */
YY_RULE_SETUP
{ ECH; return ABSTRACT; }
	YY_BREAK
case 32:
/* rule 32 can match eol */
YY_RULE_SETUP
{ ECH; return ATTRIBUTEFORMDEFAULT; }
	YY_BREAK
case 33:
/* rule 33 can match eol */
YY_RULE_SETUP
{ ECH; return BASE; }
	YY_BREAK
case 34:
/* rule 34 can match eol */
YY_RULE_SETUP
{ ECH; return DEFALT; }
	YY_BREAK
case 35:
/* rule 35 can match eol */
YY_RULE_SETUP
{ ECH; return ELEMENTFORMDEFAULT; }
	YY_BREAK
case 36:
/* rule 36 can match eol */
YY_RULE_SETUP
{ ECH; return ENCODING; }
	YY_BREAK
case 37:
/* rule 37 can match eol */
YY_RULE_SETUP
{ ECH; return FINAL; }
	YY_BREAK
case 38:
/* rule 38 can match eol */
YY_RULE_SETUP
{ ECH; return FIXED; }
	YY_BREAK
case 39:
/* rule 39 can match eol */
YY_RULE_SETUP
{ ECH; return FORM; }
	YY_BREAK
case 40:
/* rule 40 can match eol */
YY_RULE_SETUP
{ ECH; return ID; }
	YY_BREAK
case 41:
/* rule 41 can match eol */
YY_RULE_SETUP
{ ECH; return ITEMTYPE; }
	YY_BREAK
case 42:
/* rule 42 can match eol */
YY_RULE_SETUP
{ ECH; return MAXOCCURS; }
	YY_BREAK
case 43:
/* rule 43 can match eol */
YY_RULE_SETUP
{ ECH; return MINOCCURS; }
	YY_BREAK
case 44:
/* rule 44 can match eol */
YY_RULE_SETUP
{ ECH; return MIXED; }
	YY_BREAK
case 45:
/* rule 45 can match eol */
YY_RULE_SETUP
{ ECH; return NAME; }
	YY_BREAK
case 46:
/* rule 46 can match eol */
YY_RULE_SETUP
{ ECH; return NILLABLE; }
	YY_BREAK
case 47:
/* rule 47 can match eol */
YY_RULE_SETUP
{ ECH; return REFER; }
	YY_BREAK
case 48:
/* rule 48 can match eol */
YY_RULE_SETUP
{ ECH; return REF; }
	YY_BREAK
case 49:
/* rule 49 can match eol */
YY_RULE_SETUP
{ ECH; return SCHEMALOCATION; }
	YY_BREAK
case 50:
/* rule 50 can match eol */
YY_RULE_SETUP
{ ECH; return SOURCE; }
	YY_BREAK
case 51:
/* rule 51 can match eol */
YY_RULE_SETUP
{ ECH; return SUBSTITUTIONGROUP; }
	YY_BREAK
case 52:
/* rule 52 can match eol */
YY_RULE_SETUP
{ ECH; return TYP; }
	YY_BREAK
case 53:
/* rule 53 can match eol */
YY_RULE_SETUP
{ ECH; return USE; }
	YY_BREAK
case 54:
/* rule 54 can match eol */
YY_RULE_SETUP
{ ECH;
                                  if (inPatEnum) BEGIN PATENUMVALUE;
                                  return VALUE;
                                }
	YY_BREAK
case 55:
/* rule 55 can match eol */
YY_RULE_SETUP
{ ECH; return VERSION; }
	YY_BREAK
case 56:
/* rule 56 can match eol */
YY_RULE_SETUP
{ ECH; BEGIN(STRING); return XPATH; }
	YY_BREAK
case 57:
YY_RULE_SETUP
{ ECH; return XSANNOTATION; }
	YY_BREAK
case 58:
YY_RULE_SETUP
{ ECH; BEGIN(STARTDOC); return XSAPPINFO; }
	YY_BREAK
case 59:
YY_RULE_SETUP
{ ECH; return XSATTRIBUTE; }
	YY_BREAK
case 60:
YY_RULE_SETUP
{ ECH; return XSATTRIBUTEGROUP; }
	YY_BREAK
case 61:
YY_RULE_SETUP
{ ECH; return XSCHOICE; }
	YY_BREAK
case 62:
YY_RULE_SETUP
{ ECH; return XSCOMPLEXCONTENT; }
	YY_BREAK
case 63:
YY_RULE_SETUP
{ ECH; return XSCOMPLEXTYPE; }
	YY_BREAK
case 64:
YY_RULE_SETUP
{ ECH; BEGIN(STARTDOC); return XSDOCUMENTATION; }
	YY_BREAK
case 65:
YY_RULE_SETUP
{ ECH; return XSELEMENT; }
	YY_BREAK
case 66:
YY_RULE_SETUP
{ ECH; inPatEnum = 1; return XSENUMERATION; }
	YY_BREAK
case 67:
YY_RULE_SETUP
{ ECH; return XSEXTENSION; }
	YY_BREAK
case 68:
YY_RULE_SETUP
{ ECH; return XSFIELD; }
	YY_BREAK
case 69:
YY_RULE_SETUP
{ ECH; return XSGROUP; }
	YY_BREAK
case 70:
YY_RULE_SETUP
{ ECH; return XSINCLUDE; }
	YY_BREAK
case 71:
YY_RULE_SETUP
{ ECH; return XSKEY; }
	YY_BREAK
case 72:
YY_RULE_SETUP
{ ECH; return XSKEYREF; }
	YY_BREAK
case 73:
YY_RULE_SETUP
{ ECH; return XSLENGTH; }
	YY_BREAK
case 74:
YY_RULE_SETUP
{ ECH; return XSLIST; }
	YY_BREAK
case 75:
YY_RULE_SETUP
{ ECH; return XSMAXEXCLUSIVE; }
	YY_BREAK
case 76:
YY_RULE_SETUP
{ ECH; return XSMAXINCLUSIVE; }
	YY_BREAK
case 77:
YY_RULE_SETUP
{ ECH; return XSMAXLENGTH; }
	YY_BREAK
case 78:
YY_RULE_SETUP
{ ECH; return XSMINEXCLUSIVE; }
	YY_BREAK
case 79:
YY_RULE_SETUP
{ ECH; return XSMININCLUSIVE; }
	YY_BREAK
case 80:
YY_RULE_SETUP
{ ECH; return XSMINLENGTH; }
	YY_BREAK
case 81:
YY_RULE_SETUP
{ ECH; inPatEnum = 1; return XSPATTERN; }
	YY_BREAK
case 82:
YY_RULE_SETUP
{ ECH; return XSRESTRICTION; }
	YY_BREAK
case 83:
YY_RULE_SETUP
{ ECH; return XSSCHEMA; }
	YY_BREAK
case 84:
YY_RULE_SETUP
{ ECH; return XSSELECTOR; }
	YY_BREAK
case 85:
YY_RULE_SETUP
{ ECH; return XSSEQUENCE; }
	YY_BREAK
case 86:
YY_RULE_SETUP
{ ECH; return XSSIMPLECONTENT; }
	YY_BREAK
case 87:
YY_RULE_SETUP
{ ECH; return XSSIMPLETYPE; }
	YY_BREAK
case 88:
YY_RULE_SETUP
{ ECH; return XSUNIQUE; }
	YY_BREAK
case 89:
YY_RULE_SETUP
{ ECH; return BAD; }
	YY_BREAK
case 90:
YY_RULE_SETUP
ECHO;
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(COMMENT):
case YY_STATE_EOF(DOC):
case YY_STATE_EOF(ENDDOC):
case YY_STATE_EOF(PATENUMVALUE):
case YY_STATE_EOF(PREFIXED):
case YY_STATE_EOF(STARTDOC):
case YY_STATE_EOF(STRING):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 629 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 629 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 628);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param bytes the byte buffer to scan
 * @param len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

int yywrap()
{
  return 1;
}

