commandParser: src/Pose.h           \
               src/canonicalMsg.hh  \
               src/canonicalMsg.cc  \
               src/commandParser.hh \
               src/commandParser.cc \
               src/commandParserMain.cc
	/usr/bin/g++ -v -g -Wall -o $@ src/commandParserMain.cc \
                                       src/commandParser.cc     \
                                       src/canonicalMsg.cc
