commandParser: source/Pose.h           \
               source/canonicalMsg.hh  \
               source/canonicalMsg.cc  \
               source/commandParser.hh \
               source/commandParser.cc \
               source/commandParserMain.cc
	/usr/bin/g++ -v -g -Wall -o $@ source/commandParserMain.cc \
                                       source/commandParser.cc     \
                                       source/canonicalMsg.cc
